### ISSUE TITLE
Classification 3d volume

### ISSUE THREAD

**Issue by Aki1987** [Microsoft/O-CNN#10]
When I trained 2 categories: big and small depend on object's volume, I couldn't detect these categories as well as shape detection. Any body can help me solve this problem. Thank you very much!

**Comment by wang-ps** [comment]
I could not understand your problem. What do you mean by "I couldn't detect these categories as well as shape detection."? Could you explain more clearly?

**Comment by Aki1987** [comment]
Sory for my question. I used your caffemodel to classifier 40 categories with very good results. Then I recognize about object scale. I have two categories are big and small, ignore object's class. I trained in big category with many objects with big volume and in small category with same objects with small volume. However the prediction is not so good.

**Comment by Aki1987** [comment]
Thanks. You really help me so much.
