### ISSUE TITLE
Pytorch code for autoencoder

### ISSUE THREAD

**Issue by ShilinC** [microsoft/O-CNN#100]
Hi,

I saw the initial Pytorch version of O-CNN you just released. That's wonderful! I'm wondering if there's any plan to release a Pytorch version of the shape autoencoder (or any other) so we can also have the decoder part? Thanks! These are great works.

Regards,
Shilin

**Comment by wang-ps** [comment]
Thanks for your interest in our project. 
Sure! Recently I am busy with another project, and I will write the code for 3D autoencoder in the next few months.

**Comment by ShilinC** [comment]
Thanks!
