### ISSUE TITLE
TF Semantic Segmentation with UNet

### ISSUE THREAD

**Issue by migari01** [microsoft/O-CNN#103]
Hello,

I have been trying to run your code for semantic segmentation with UNet on the Bed and Bottle dataset you provided, and the network does not seem to converge. I have used the same configuration as [HRNet config](https://github.com/microsoft/O-CNN/blob/master/tensorflow/script/configs/seg_hrnet_partnet_pts.yaml), but changed option model from "hrnet" to "unet".
Did you use a different configuration for your experiments? If yes, could you please share it? 

Also, is [this network](https://github.com/microsoft/O-CNN/blob/master/tensorflow/script/network_unet.py) the equivalent of Caffe O-CNN version for segmentation?  Are there any significant differences?

Thank you

**Comment by jeichelbaum** [comment]
If I understand both networks correctly, then one of the major differences is that the Tensorflow unet uses residual blocks and is potentially much deeper than the shallow Caffe segmentation network. The author will probably be able to give a more conclusive answer though.

**Comment by wang-ps** [comment]
Yes, the tensorflow-based UNet is deeper with resblocks and its performance is also better.  
What do you mean by "does not seem to converge"? Can you run the experiments using HRNet with the instructions [here](https://github.com/microsoft/O-CNN/blob/master/docs/segmentation.md#shape-segmentation-on-partnet-with-tensorflow)?
