### ISSUE TITLE
Revert lmdb file to octree files

### ISSUE THREAD

**Issue by jeichelbaum** [microsoft/O-CNN#104]
In your [data preparation](https://github.com/microsoft/O-CNN/blob/master/docs/data_preparation.md) section you are referencing the "revert_octree_data" tool that can revert a lmdb file to the original octree files. The problem is I can't find this tool anywhere in caffe/tools. The only tool present is "convert_octree_data". Do you still have the original "revert_octree_data" tool? 

Thanks in advance

**Comment by wang-ps** [comment]
I have uploaded the cpp file just now. Please pull the latest code.

**Comment by jeichelbaum** [comment]
thank you, much appreciated :)
