### ISSUE TITLE
单个3D数据大小问题

### ISSUE THREAD

**Issue by zhDai** [microsoft/O-CNN#109]
你好，如果我的3D模型的面比较多，比如有30w。那我可以直接拿ocnn训练吗，而不需要做一些下采样的工作，以此来减少面的个数。

**Comment by jeichelbaum** [comment]
對不起我的中文: 你不需要做下采样, o-cnn 用從3D模型中採樣的點雲

As far as I understand the number of faces doesn't matter and you don't have to downsample the 3D object. All networks in this repository work on point clouds / octrees sampled from point clouds

**Comment by zhDai** [comment]
> 對不起我的中文: 你不需要做下采样, o-cnn 用從3D模型中採樣的點雲
> 
> As far as I understand the number of faces doesn't matter and you don't have to downsample the 3D object. All networks in this repository work on point clouds directly or on octrees sampled from point clouds

yeah，thanks a lot

**Comment by zhDai** [comment]
> 對不起我的中文: 你不需要做下采样, o-cnn 用從3D模型中採樣的點雲
> 
> As far as I understand the number of faces doesn't matter and you don't have to downsample the 3D object. All networks in this repository work on point clouds directly or on octrees sampled from point clouds

hello jeichelbaum, can you help me how to prepare the data for Segmentation? I don‘t understand how to make the labels into file like *.points

**Comment by jeichelbaum** [comment]
I haven't run the segmentation experiment yet, so I can't give you definite answers, but only provide some pointers. From what I can see the code in [tensorflow/data/seg_parnet.py](https://github.com/microsoft/O-CNN/blob/master/tensorflow/data/seg_partnet.py) handles the preprocessing sequence: ply -> points -> fuse with labels -> store in tfrecords

I believe that the method `convert_single_data` fuses .points with labels, so you could maybe try to change the file paths to fit your dataset or replicate the functionality of the method? 

Sorry that I can't give a better answer at the moment.

**Comment by zhDai** [comment]
> I haven't run the segmentation experiment yet, so I can't give you definite answers, but I can provide some pointers. From what I can see the code in [tensorflow/data/seg_parnet.py](https://github.com/microsoft/O-CNN/blob/master/tensorflow/data/seg_partnet.py) handles the preprocessing sequence: ply -> fuse with labels -> convert to points -> store in tfrecords
> 
> I believe that the method `convert_single_data` fuses .points with labels, so you could maybe try to change the file paths to fit your dataset or replicate the functionality of the method?
> 
> Sorry that I can't give a better answer at the moment.

Thanks for your reply. I also see the seg_parnet.py, then I can't understand the meaning of 'level_list_list' and 'finest_level'. Can you have some ideas about it?

**Comment by wang-ps** [comment]
Please refer to the instructions [here](https://github.com/microsoft/O-CNN/blob/master/docs/data_preparation.md#custom-data) to prepare the data for segmentation. Explicitly, you should store the point label into  `vector<float> labels` .

On the other hand, you can also save the point labels into the `ply` files, and use the tool `ply2points` to create the points files.

**Comment by zhDai** [comment]
> Please refer to the instructions [here](https://github.com/microsoft/O-CNN/blob/master/docs/data_preparation.md#custom-data) to prepare the data for segmentation. Explicitly, you should store the point label into `vector<float> labels` .
> 
> On the other hand, you can also save the point labels into the `ply` files, and use the tool `ply2points` to create the points files.

hi！I have built the caffe with ocnn. But when I do "make test", the errors comes：
src/caffe/test/test_octree2col_layer.cpp:30:17: error: 'blob_bottom_' was not declared in this scope
     filler.Fill(blob_bottom_);
                 ^~~~~~~~~~~~
src/caffe/test/test_octree2col_layer.cpp:30:17: note: suggested alternative: 'BlobProto'
     filler.Fill(blob_bottom_);
                 ^~~~~~~~~~~~
                 BlobProto
src/caffe/test/test_octree2col_layer.cpp: In instantiation of 'void caffe::Octree2ColTest<TypeParam>::SetUp() [with TypeParam = caffe::GPUDevice<double>]':
src/caffe/test/test_octree2col_layer.cpp:152:1:   required from here
src/caffe/test/test_octree2col_layer.cpp:16:5: error: cannot bind non-const lvalue reference of type 'std::vector<std::__cxx11::basic_string<char> >&' to an rvalue of type 'std::vector<std::__cxx11::basic_string<char> >'
     this->load_test_data(vector<string> {"octree_1"});
     ^~~~
In file included from src/caffe/test/test_octree2col_layer.cpp:2:0:
./include/caffe/test/test_octree.hpp:62:8: note:   initializing argument 1 of 'void caffe::OctreeTest<TypeParam>::load_test_data(std::vector<std::__cxx11::basic_string<char> >&) [with TypeParam = caffe::GPUDevice<double>]'
   void load_test_data(vector<string>& data_names) {
        ^~~~~~~~~~~~~~
src/caffe/test/test_octree2col_layer.cpp: In instantiation of 'void caffe::Octree2ColTest<TypeParam>::SetUp() [with TypeParam = caffe::GPUDevice<float>]':
src/caffe/test/test_octree2col_layer.cpp:152:1:   required from here
src/caffe/test/test_octree2col_layer.cpp:16:5: error: cannot bind non-const lvalue reference of type 'std::vector<std::__cxx11::basic_string<char> >&' to an rvalue of type 'std::vector<std::__cxx11::basic_string<char> >'
     this->load_test_data(vector<string> {"octree_1"});
     ^~~~
In file included from src/caffe/test/test_octree2col_layer.cpp:2:0:
./include/caffe/test/test_octree.hpp:62:8: note:   initializing argument 1 of 'void caffe::OctreeTest<TypeParam>::load_test_data(std::vector<std::__cxx11::basic_string<char> >&) [with TypeParam = caffe::GPUDevice<float>]'
   void load_test_data(vector<string>& data_names) {
        ^~~~~~~~~~~~~~
src/caffe/test/test_octree2col_layer.cpp: In instantiation of 'void caffe::Octree2ColTest<TypeParam>::SetUp() [with TypeParam = caffe::CPUDevice<double>]':
src/caffe/test/test_octree2col_layer.cpp:152:1:   required from here
src/caffe/test/test_octree2col_layer.cpp:16:5: error: cannot bind non-const lvalue reference of type 'std::vector<std::__cxx11::basic_string<char> >&' to an rvalue of type 'std::vector<std::__cxx11::basic_string<char> >'
     this->load_test_data(vector<string> {"octree_1"});
     ^~~~
In file included from src/caffe/test/test_octree2col_layer.cpp:2:0:
./include/caffe/test/test_octree.hpp:62:8: note:   initializing argument 1 of 'void caffe::OctreeTest<TypeParam>::load_test_data(std::vector<std::__cxx11::basic_string<char> >&) [with TypeParam = caffe::CPUDevice<double>]'
   void load_test_data(vector<string>& data_names) {
        ^~~~~~~~~~~~~~
src/caffe/test/test_octree2col_layer.cpp: In instantiation of 'void caffe::Octree2ColTest<TypeParam>::SetUp() [with TypeParam = caffe::CPUDevice<float>]':
src/caffe/test/test_octree2col_layer.cpp:152:1:   required from here
src/caffe/test/test_octree2col_layer.cpp:16:5: error: cannot bind non-const lvalue reference of type 'std::vector<std::__cxx11::basic_string<char> >&' to an rvalue of type 'std::vector<std::__cxx11::basic_string<char> >'
     this->load_test_data(vector<string> {"octree_1"});
     ^~~~
In file included from src/caffe/test/test_octree2col_layer.cpp:2:0:
./include/caffe/test/test_octree.hpp:62:8: note:   initializing argument 1 of 'void caffe::OctreeTest<TypeParam>::load_test_data(std::vector<std::__cxx11::basic_string<char> >&) [with TypeParam = caffe::CPUDevice<float>]'
   void load_test_data(vector<string>& data_names) {
        ^~~~~~~~~~~~~~
Makefile:586: recipe for target '.build_release/src/caffe/test/test_octree2col_layer.o' failed
make: *** [.build_release/src/caffe/test/test_octree2col_layer.o] Error 1

can u help me？

**Comment by jeichelbaum** [comment]
I get the same errors when I run `make test` after building Caffe, but this has no impact on the functionality of the O-CNN as far as I can tell. You can verify this by running the [shape classification](https://github.com/microsoft/O-CNN/blob/master/docs/classification.md) experiment.

**Comment by zhDai** [comment]
> Are you refering to `make runtest` inside the Caffe/build directory? I get the same errors when I run `make runtest` after building Caffe, but this has no impact on the functionality of the O-CNN as far as I can tell. You can verify this by running the [shape classification](https://github.com/microsoft/O-CNN/blob/master/docs/classification.md) experiment.
> 
> Did you follow the instructions in the [installations doc](https://github.com/microsoft/O-CNN/blob/master/docs/installation.md) and copy the o-cnn/caffe files into the caffe directory before building?

yes. BUT I suggest you use Dockerfile to ocnn.
