### ISSUE TITLE
Part-Segmentation

### ISSUE THREAD

**Issue by Aki1987** [Microsoft/O-CNN#11]
Thank you for your great works.
Can I ask you how to generate part-segmentation model as displaying in Fig.9 in your paper.
I know we need to input segmentation label to lmdb database, but I dont know how to do this.
Can you show me structure of data before converting them to segmentation database.

Thank you very much.

**Comment by wang-ps** [comment]
The fig. 9 is generated by OpenGL. Render the point cloud,  using the segmentation label as the color.

For the structure of the data, please refer to the function `void load_pointcloud()` defined in Line 141 in the file `octree/Octree/main.cpp`

**Comment by Aki1987** [comment]
Sorry, Can I ask you one more quenstion in this issue.
I've seen that there is a 3d points file with segmentation which line contains condinates plus colors (XYZRGB). But this file is pts or txt file, can not used in convert_to_octree program you provided.
Please explain more detail about this problem.
Thank you.

**Comment by wang-ps** [comment]
The program `convert_to_octree` is used to convert the `octree` files into `lmdb` database. The input of this program should be the `octree` files.
