### ISSUE TITLE
ImportError: undefined symbol

### ISSUE THREAD

**Issue by AustereTriceratops** [microsoft/O-CNN#110]
I was able to build the program, but I run into a problem when testing. I get the following output from the command ```python -W ignore test/test_octree_property.py -v```:

```
Traceback (most recent call last):
  File "test/test_octree_property.py", line 3, in <module>
    import ocnn
  File "/home/levi/anaconda3/envs/oacnn/lib/python3.7/site-packages/ocnn-1.0-py3.7-linux-x86_64.egg/ocnn/__init__.py", line 4, in <module>
    from . import nn
ImportError: /home/levi/anaconda3/envs/oacnn/lib/python3.7/site-packages/ocnn-1.0-py3.7-linux-x86_64.egg/ocnn/nn.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6octree14OctreeBaseConvIfE16forward_gpu_gemmEPfPKfS4_
```

This also happens when I call any of the other test files. I'm not sure how exactly to troubleshoot this further. I'd appreciate any advice.

**Comment by jeichelbaum** [comment]
Just to make sure, you trying to install the pytorch version and followed all steps in [docs/installation](https://github.com/microsoft/O-CNN/blob/master/docs/installation.md)?

**Comment by AustereTriceratops** [comment]
Right, I ran the octree installation first then moved onto the pytorch section. Here's my environment.

operating system: Ubuntu version of WSL 2
gcc: 9.3.0
CUDA: N/A (installed with the USE_CUDA option off, so the language(s) should be set to Cxx)

**Comment by wang-ps** [comment]
Currently, the pytorch-based ocnn code can only be compiled with CUDA enabled. The code with CPU mode has not been implemented.
