### ISSUE TITLE
How to use DenseCRF to refine point cloud

### ISSUE THREAD

**Issue by zhDai** [microsoft/O-CNN#117]
HI，I have trained a model about Shape Segmentation. Then I want to use DenseCRF,but I found that you use "probo.txt". So can you show me what is it？And how to make it？Looking forward to your reply.

**Comment by wang-ps** [comment]
I did not touch the code for 4 years. And please read the code to find the details.
I suggest using our tensorflow-based implementation for shape segmentation. It can produce good results even without DenseCRF.
