### ISSUE TITLE
Issue with implementation of loss_function_seg() in ocnn.py

### ISSUE THREAD

**Issue by rnpatien** [microsoft/O-CNN#118]
I was getting incorrect results for label_mask when I change ">" to use tf.greater that corrected the problem.

After the change there was an improvement to the rate of convergence.

Note the following comment about using python logic operations https://stackoverflow.com/questions/57056951/using-conditional-expressions-for-tensorflow

**Comment by wang-ps** [comment]
Thanks, I will fix this issue in the future commits.
