### ISSUE TITLE
Is there any plan for implementing multi-gpu version of pytorch model?

### ISSUE THREAD

**Issue by SuekyeongNam** [microsoft/O-CNN#119]
I realized that there is no module for multi-gpu because of the structure of octree.
Is there any plan for implementing multi-gpu version of pytorch model?

Additionally, do you have a plan for publishing autoencoder model using pytorch?

**Comment by wang-ps** [comment]
In theory, the multi-gpu mode can be implemented. And I will release the code in the near future.
