### ISSUE TITLE
Status of building under Windows 10

### ISSUE THREAD

**Issue by jjholt42** [microsoft/O-CNN#121]
We really need to be able to run under Windows 10. We can built the octree tools, but the tensoflow part is hard coded to Linux. Do you have any plans to support build under windows? Or do you have any suggestions or non-working code that might help? Thanks.

**Comment by wang-ps** [comment]
Sorry, I have not tried the code on Win10. And I did find instructions on the compiling of custom ops on Windows in the tutorial of [Tensorflow](https://www.tensorflow.org/guide/create_op#compile_the_op_using_your_system_compiler_tensorflow_binary_installation).
