### ISSUE TITLE
Pytorch unpooling layer

### ISSUE THREAD

**Issue by akgoins** [microsoft/O-CNN#123]
I am trying to create an autoencoder in Pytorch and I am seeing several issues with the unpooling layer.  To debug the issue, I made a very simple network as follows:

```
kernel_size = [3]
stride = 1
        
conv1 =   ocnn.OctreeConvBnRelu(4, 1, 8, kernel_size, stride)
pool1 =   ocnn.OctreeMaxPool(4)
conv2 =   ocnn.OctreeConvBnRelu(3, 8, 16, kernel_size, stride)
unpool1 = ocnn.OctreeMaxUnpool(3)
conv3 =   ocnn.OctreeConvBnRelu(4, 16, 1, kernel_size, stride)
```

When I perform the forward pass through all of the layers, I get the following error:
```
[F octree_pool.cpp:44] Check failed: top_h == octree_.info().node_num_nempty(depth - 1) (16 vs. 8) 
```

If I change the depth of the unpooling layer to 4, I start getting errors during the depad step:
```
[F octree_pad.cpp:62] Check failed: octree_.info().node_num(depth_) == top_h (128 vs. 64) , depad, d = 4, channel = 16
```

After looking at the code, it appears that the check of `octree_pool.cpp:44` is supposed to look at the top layer.  For a pool layer of depth 4, the top layer would have depth 3.  For an unpool layer of depth 3, the top layer would be depth 4.  But since the current depth of the layer is fed in, then the check on line 44 for an unpooling layer would actually be checking for a depth of 2, not 4 like it should be.

If I am correct in my understanding, then octree_pool.cpp:44 should be:
```
CHECK_EQ(top_h, octree_.info().node_num_nempty(depth));
```

And the appropriate depth offsets should be applied in `ocnn/octree_pool.py` where it is call.
To check the top layer of the polling layer, change `octree_pool.py:21` to:
```
grad_out = ocnn.nn.octree_max_unpool(grad_in, mask, octree, ctx.depth - 1)
```

To check the top layer of the unpolling layer, change `octree_pool.py:30` to:
```
grad_out = ocnn.nn.octree_max_unpool(grad_in, mask, octree, ctx.depth + 1)
```

I recompiled with these changes and was able to get my simple network to train successfully.
Does this all sound correct to you?  I have some other issues with my network and unpooling layers, but I wanted to make sure that my understand of this was correct before I tried to solve my other problems.

**Comment by wang-ps** [comment]
Thank you for your interest in our project. I will update an example using the unpool soon.

**Comment by wang-ps** [comment]
@akgoins 
Hi, I have released the code which uses the  pytorch-based unpooling layer for shape segmentation. Please pull the latest code and refer to the instructions [here](https://github.com/microsoft/O-CNN/blob/master/docs/segmentation.md#shape-segmentation-on-shapenet-with-pytorch) to have a try.
The C++ code should not be modified. And there is indeed a bug in the python code [here](https://github.com/microsoft/O-CNN/blob/10772672f9e1141ddf124ceda5fdccc6cd6fdcb2/pytorch/ocnn/octree_pool.py#L93), and I have fixed it.
