### ISSUE TITLE
Unable to download shape completion data

### ISSUE THREAD

**Issue by tangjiaheng** [microsoft/O-CNN#126]
[The data download url](https://www.dropbox.com/s/y5ljm2bs8649j3p/ocnn_completion.zip?dl=0) is invalid. If possible, I hope you can provide an other way to obtain data. Thank you very much!

**Comment by wang-ps** [comment]
Please download the data via the following link:
https://www.dropbox.com/s/z2x0mw4ai18f855/ocnn_completion.zip?dl=0

The data is hosted by a free dropbox account. The original link is disabled by dropbox due to large network traffic. Please do not download it too frequently.
