### ISSUE TITLE
CUDA error! when try to run pytorch/projects/classification.py in cpu.

### ISSUE THREAD

**Issue by TrepangCat** [microsoft/O-CNN#131]
I manually edit pytorch/projects/classification.py to run it in cpu mode by using .to('cpu')
But CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)` occurs when ocnn.nn.octree_conv() is runing.
Why?

**Comment by wang-ps** [comment]
Sorry, currently for octree_conv in PyTorch,  the cpu mode is not supported.

The basic implement of cpu-based octree_conv exists in the library `octree`,  however, the interfaces are not exposed to PyTorch.

**Comment by TrepangCat** [comment]
Thanks
