### ISSUE TITLE
404 error when download shape completion data

### ISSUE THREAD

**Issue by MisEty** [microsoft/O-CNN#138]
I want to get the shape completion data from https://www.dropbox.com/s/z2x0mw4ai18f855/ocnn_completion.zip?dl=0, but get 404 error.  I hope you can provide another way to download the data. Thanks!

**Comment by wang-ps** [comment]
The data is hosted by a free Dropbox account. The original link is temporarily disabled by Dropbox due to large network downloading traffic. 
Please wait for several days and download it again, and do not download it too frequently.  Sorry for the inconvenience.
