### ISSUE TITLE
how to prepare data if my point cloud has no normal information

### ISSUE THREAD

**Issue by gaoshang100** [Microsoft/O-CNN#14]
hi i am new 
1: i want to know if my point cloud has no normal information, how to prepare my input data and where i have to modify, whether is the input data channel?
2: how to convert the final result to point cloud?

**Comment by Aki1987** [comment]
@gaoshang100 Same with me. Please show me if you have solved these problems.

**Comment by wang-ps** [comment]
If the normal is not available, estimate it from the point cloud or simply set it to (0, 0, 1). 
For the pointcloud file format, please refer to the readme on this [page](https://github.com/wang-ps/O-CNN/tree/master/virtual%20scanner).

**Comment by bensnell** [comment]
Another option for generating normal information from point clouds is to use the command line tool **meshlabserver**, which can be downloaded by installing the program [MeshLab](http://www.meshlab.net/).

Within the program MeshLab, the algorithm under _Filters_ > _Normals, Curvatures and Orientation_ > _Compute normals for point sets_ will compute normals. This action can be automated through the command line by saving this script (_Filters_ > _Show Current Script_ > _Save Script_) and running the tool meshlabserver according to the instructions [here](https://github.com/cnr-isti-vclab/meshlab/blob/master/src/meshlabserver/meshlabserver.txt).

**Comment by lxxue** [comment]
If I just want to use point cloud without normal information, I just need to set
`		Vector3F n = p01.cross(p02);`
in https://github.com/wang-ps/O-CNN/blob/bbcf7e28e8500024a000b6b15eecd24652d6e11d/virtual_scanner/VirtualScanner/VirtualScanner.cpp#L194
to be 
`		Vector3F n(0.0, 0.0, 1.0);`

is it correct?

**Comment by wang-ps** [comment]
Yes, you are right.
With normal as (0, 0, 1), the octree can also be built. 
But the performance of calssification will drop.
