### ISSUE TITLE
error testing O-CNN under pytorch after building

### ISSUE THREAD

**Issue by chih-yu-chen** [microsoft/O-CNN#144]
Hi, I'm building O-CNN on a docker container with cuda 11.3, Python 3.8.8, pytorch-quantization 2.1.0, pytorch-transformers 1.1.0, torchvision 0.9.0a0, and cudatoolkit 10.2.89 installed. Building works well, but when I run the test cases, I get the following errors. It seems something is wrong when importing nn. How can I solve this error? Thank you so much in advance!

--

$ python -W ignore test/test_all.py -v
Traceback (most recent call last):
  File "test/test_all.py", line 3, in <module>
    from test_octree_conv import OctreeConvTest
  File "/workspace/lidar/windows-doors/O-CNN/pytorch/test/test_octree_conv.py", line 3, in <module>
    import ocnn
  File "/opt/conda/lib/python3.8/site-packages/ocnn-1.0-py3.8-linux-x86_64.egg/ocnn/__init__.py", line 4, in <module>
    from . import nn
ImportError: /opt/conda/lib/python3.8/site-packages/ocnn-1.0-py3.8-linux-x86_64.egg/ocnn/nn.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK10PointsInfo12check_formatERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by wang-ps** [comment]
Sorry, I can not reproduce your error. 

Please try the official docker provided by pytorch: `docker pull pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel`
And here is the ocnn docker I built based on the official pytorch docker: `docker pull wangps/ocnn:pytorch-1.9.0`
