### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by zhexinXie** [microsoft/O-CNN#145]
I built octree in your docker: **docker pull wangps/ocnn:pytorch-1.9.0**, but the error occurred. here is build log
I don't know why. Hope for you help.
and I want to know whether the ocnn can only be built in ubuntu? When I run setup.py in Win10, there are so many errors.

(base) root@(docker)67034be3fb5a:/workspace/ocnn-pytorch
$ python setup.py install --build_octree
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
mkdir /workspace/octree/build && cd /workspace/octree/build && cmake .. -DABI=ON -DKEY64=ON  && cmake --build . --config Release && ./octree_test
-- octree: USE_CUDA
-- The CUDA compiler identification is NVIDIA 10.2.89
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- octree: CMAKE_CUDA_STANDARD=11
-- octree: _GLIBCXX_USE_CXX11_ABI=0
-- octree: USE_MINIBALL
-- octree: KEY64
-- Found PythonInterp: /opt/conda/bin/python (found version "3.7.10")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/octree/build
Scanning dependencies of target octree_lib
[  1%] Building CXX object CMakeFiles/octree_lib.dir/octree/contour.cpp.o
[  2%] Building CXX object CMakeFiles/octree_lib.dir/octree/filenames.cpp.o
[  3%] Building CXX object CMakeFiles/octree_lib.dir/octree/marching_cube.cpp.o
[  4%] Building CXX object CMakeFiles/octree_lib.dir/octree/marching_cube_table.cpp.o
[  6%] Building CXX object CMakeFiles/octree_lib.dir/octree/math_functions.cpp.o
[  7%] Building CXX object CMakeFiles/octree_lib.dir/octree/merge_octrees.cpp.o
[  8%] Building CXX object CMakeFiles/octree_lib.dir/octree/mesh.cpp.o
[  9%] Building CXX object CMakeFiles/octree_lib.dir/octree/octree.cpp.o
[ 10%] Building CXX object CMakeFiles/octree_lib.dir/octree/octree_conv.cpp.o
[ 12%] Building CXX object CMakeFiles/octree_lib.dir/octree/octree_info.cpp.o
[ 13%] Building CXX object CMakeFiles/octree_lib.dir/octree/octree_nn.cpp.o
[ 14%] Building CXX object CMakeFiles/octree_lib.dir/octree/octree_parser.cpp.o
[ 15%] Building CXX object CMakeFiles/octree_lib.dir/octree/octree_samples.cpp.o
[ 16%] Building CXX object CMakeFiles/octree_lib.dir/octree/octree_value.cpp.o
[ 18%] Building CXX object CMakeFiles/octree_lib.dir/octree/points.cpp.o
[ 19%] Building CXX object CMakeFiles/octree_lib.dir/octree/points_info.cpp.o
[ 20%] Building CXX object CMakeFiles/octree_lib.dir/octree/points_parser.cpp.o
[ 21%] Building CXX object CMakeFiles/octree_lib.dir/octree/simplify_points.cpp.o
[ 22%] Building CXX object CMakeFiles/octree_lib.dir/octree/transform_octree.cpp.o
[ 24%] Building CXX object CMakeFiles/octree_lib.dir/octree/transform_points.cpp.o
[ 25%] Building CUDA object CMakeFiles/octree_lib.dir/octree/octree_nn.cu.o
[ 26%] Building CUDA object CMakeFiles/octree_lib.dir/octree/octree_parser.cu.o
[ 27%] Linking CXX static library liboctree_lib.a
[ 27%] Built target octree_lib
Scanning dependencies of target upgrade_points
[ 28%] Building CXX object CMakeFiles/upgrade_points.dir/tools/upgrade_points.cpp.o
[ 30%] Linking CXX executable upgrade_points
[ 30%] Built target upgrade_points
Scanning dependencies of target gtest
[ 31%] Building CXX object external/octree-ext/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 32%] Linking CXX static library ../../../../lib/libgtest.a
[ 32%] Built target gtest
Scanning dependencies of target gtest_main
[ 33%] Building CXX object external/octree-ext/googletest/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 34%] Linking CXX static library ../../../../lib/libgtest_main.a
[ 34%] Built target gtest_main
Scanning dependencies of target octree_test
[ 36%] Building CXX object CMakeFiles/octree_test.dir/test/test_octree.cpp.o
[ 37%] Building CXX object CMakeFiles/octree_test.dir/test/test_octree_nn.cpp.o
[ 38%] Building CXX object CMakeFiles/octree_test.dir/test/test_util.cpp.o
[ 39%] Linking CXX executable octree_test
[ 39%] Built target octree_test
Scanning dependencies of target upgrade_octree
[ 40%] Building CXX object CMakeFiles/upgrade_octree.dir/tools/upgrade_octree.cpp.o
[ 42%] Linking CXX executable upgrade_octree
[ 42%] Built target upgrade_octree
Scanning dependencies of target transform_points
[ 43%] Building CXX object CMakeFiles/transform_points.dir/tools/transform_points.cpp.o
[ 44%] Linking CXX executable transform_points
[ 44%] Built target transform_points
Scanning dependencies of target simplify_points
[ 45%] Building CXX object CMakeFiles/simplify_points.dir/tools/simplify_points.cpp.o
[ 46%] Linking CXX executable simplify_points
[ 46%] Built target simplify_points
Scanning dependencies of target points_noise
[ 48%] Building CXX object CMakeFiles/points_noise.dir/tools/points_noise.cpp.o
[ 49%] Linking CXX executable points_noise
[ 49%] Built target points_noise
Scanning dependencies of target check_octree
[ 50%] Building CXX object CMakeFiles/check_octree.dir/tools/check_octree.cpp.o
[ 51%] Linking CXX executable check_octree
[ 51%] Built target check_octree
Scanning dependencies of target chamfer_distance
[ 53%] Building CXX object CMakeFiles/chamfer_distance.dir/tools/chamfer_distance.cpp.o
[ 54%] Linking CXX executable chamfer_distance
[ 54%] Built target chamfer_distance
Scanning dependencies of target ply2points
[ 55%] Building CXX object CMakeFiles/ply2points.dir/tools/ply2points.cpp.o
[ 56%] Linking CXX executable ply2points
[ 56%] Built target ply2points
Scanning dependencies of target octree
[ 57%] Building CXX object CMakeFiles/octree.dir/tools/build_octree.cpp.o
[ 59%] Linking CXX executable octree
[ 59%] Built target octree
Scanning dependencies of target clip_points
[ 60%] Building CXX object CMakeFiles/clip_points.dir/tools/clip_points.cpp.o
[ 61%] Linking CXX executable clip_points
[ 61%] Built target clip_points
Scanning dependencies of target adaptive_octree
[ 62%] Building CXX object CMakeFiles/adaptive_octree.dir/tools/adaptive_octree.cpp.o
[ 63%] Linking CXX executable adaptive_octree
[ 63%] Built target adaptive_octree
Scanning dependencies of target rply
[ 65%] Building C object CMakeFiles/rply.dir/external/octree-ext/rply-1.1.4/rply.c.o
[ 66%] Linking C static library librply.a
[ 66%] Built target rply
Scanning dependencies of target octree2mesh
[ 67%] Building CXX object CMakeFiles/octree2mesh.dir/tools/octree2mesh.cpp.o
[ 68%] Linking CXX executable octree2mesh
[ 68%] Built target octree2mesh
Scanning dependencies of target merge_octree
[ 69%] Building CXX object CMakeFiles/merge_octree.dir/tools/merge_octree.cpp.o
[ 71%] Linking CXX executable merge_octree
[ 71%] Built target merge_octree
Scanning dependencies of target custom_data
[ 72%] Building CXX object CMakeFiles/custom_data.dir/tools/custom_data.cpp.o
[ 73%] Linking CXX executable custom_data
[ 73%] Built target custom_data
Scanning dependencies of target octree2pts_suncg
[ 74%] Building CXX object CMakeFiles/octree2pts_suncg.dir/tools/octree2pts_suncg.cpp.o
[ 75%] Linking CXX executable octree2pts_suncg
[ 75%] Built target octree2pts_suncg
Scanning dependencies of target octree_samples
[ 77%] Building CXX object CMakeFiles/octree_samples.dir/tools/octree_samples.cpp.o
[ 78%] Linking CXX executable octree_samples
[ 78%] Built target octree_samples
Scanning dependencies of target octree_zbuffer
[ 79%] Building CXX object CMakeFiles/octree_zbuffer.dir/tools/octree_zbuffer.cpp.o
[ 80%] Linking CXX executable octree_zbuffer
[ 80%] Built target octree_zbuffer
Scanning dependencies of target bbox
[ 81%] Building CXX object CMakeFiles/bbox.dir/tools/bbox.cpp.o
[ 83%] Linking CXX executable bbox
[ 83%] Built target bbox
Scanning dependencies of target mesh2points
[ 84%] Building CXX object CMakeFiles/mesh2points.dir/tools/mesh2points.cpp.o
[ 85%] Linking CXX executable mesh2points
[ 85%] Built target mesh2points
Scanning dependencies of target octree2points
[ 86%] Building CXX object CMakeFiles/octree2points.dir/tools/octree2points.cpp.o
[ 87%] Linking CXX executable octree2points
[ 87%] Built target octree2points
Scanning dependencies of target octree_bbox
[ 89%] Building CXX object CMakeFiles/octree_bbox.dir/tools/octree_bbox.cpp.o
[ 90%] Linking CXX executable octree_bbox
[ 90%] Built target octree_bbox
Scanning dependencies of target octree_prune
[ 91%] Building CXX object CMakeFiles/octree_prune.dir/tools/octree_prune.cpp.o
[ 92%] Linking CXX executable octree_prune
[ 92%] Built target octree_prune
Scanning dependencies of target octree_dropout
[ 93%] Building CXX object CMakeFiles/octree_dropout.dir/tools/octree_dropout.cpp.o
[ 95%] Linking CXX executable octree_dropout
[ 95%] Built target octree_dropout
Scanning dependencies of target points2ply
[ 96%] Building CXX object CMakeFiles/points2ply.dir/tools/points2ply.cpp.o
[ 97%] Linking CXX executable points2ply
[ 97%] Built target points2ply
Scanning dependencies of target play_ground
[ 98%] Building CXX object CMakeFiles/play_ground.dir/tools/play_ground.cpp.o
[100%] Linking CXX executable play_ground
[100%] Built target play_ground
Running main() from /workspace/octree/external/octree-ext/googletest/googletest/src/gtest_main.cc
[==========] Running 12 tests from 7 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from OctreeTest
[ RUN      ] OctreeTest.TestOctreeBuild
[       OK ] OctreeTest.TestOctreeBuild (0 ms)
[ RUN      ] OctreeTest.TestOctreeTrim
[       OK ] OctreeTest.TestOctreeTrim (0 ms)
[----------] 2 tests from OctreeTest (0 ms total)

[----------] 1 test from VecResizeTest
[ RUN      ] VecResizeTest.TestVecResize
[       OK ] VecResizeTest.TestVecResize (0 ms)
[----------] 1 test from VecResizeTest (0 ms total)

[----------] 1 test from BiliearNeigh
[ RUN      ] BiliearNeigh.TestBiliearNeigh
[       OK ] BiliearNeigh.TestBiliearNeigh (0 ms)
[----------] 1 test from BiliearNeigh (1 ms total)

[----------] 1 test from Coord2xyzTest
[ RUN      ] Coord2xyzTest.TestCoord2xyz
[       OK ] Coord2xyzTest.TestCoord2xyz (0 ms)
[----------] 1 test from Coord2xyzTest (0 ms total)

[----------] 3 tests from UtilTest
[ RUN      ] UtilTest.TestExtractPath
[       OK ] UtilTest.TestExtractPath (0 ms)
[ RUN      ] UtilTest.TestExtractFilename
[       OK ] UtilTest.TestExtractFilename (0 ms)
[ RUN      ] UtilTest.TestExtractSuffix
[       OK ] UtilTest.TestExtractSuffix (0 ms)
[----------] 3 tests from UtilTest (0 ms total)

[----------] 2 tests from MeshTest
[ RUN      ] MeshTest.TestFaceCenter
[       OK ] MeshTest.TestFaceCenter (0 ms)
[ RUN      ] MeshTest.TestFaceNormal
[       OK ] MeshTest.TestFaceNormal (0 ms)
[----------] 2 tests from MeshTest (0 ms total)

[----------] 2 tests from MathTest
[ RUN      ] MathTest.TestRotMatrix1
[       OK ] MathTest.TestRotMatrix1 (0 ms)
[ RUN      ] MathTest.TestRotMatrix2
[       OK ] MathTest.TestRotMatrix2 (0 ms)
[----------] 2 tests from MathTest (1 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 7 test suites ran. (2 ms total)
[  PASSED  ] 12 tests.
running install
running bdist_egg
running egg_info
writing ocnn.egg-info/PKG-INFO
writing dependency_links to ocnn.egg-info/dependency_links.txt
writing requirements to ocnn.egg-info/requires.txt
writing top-level names to ocnn.egg-info/top_level.txt
reading manifest file 'ocnn.egg-info/SOURCES.txt'
writing manifest file 'ocnn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'ocnn.nn' extension
Emitting ninja build file /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
g++ -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree2col.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/transform_points.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/points_property.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_key.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_batch.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_grow.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_align.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/point2octree.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_pool.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/transform_octree.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_property.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_pad.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_conv.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/pybind.o /workspace/ocnn-pytorch/build/temp.linux-x86_64-3.7/./cpp/octree_samples.o -L/workspace/octree/build -L/opt/conda/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -loctree_lib -lcublas -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/ocnn/nn.cpython-37m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/transforms.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/octree2voxel.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/nn.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/octree_conv.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/octree2col.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/ounet.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/octree_interp.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/unet.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/octree_pool.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/resnet.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/lenet.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/octree_pad.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/segnet.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/modules.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/mlp.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/octree_align.py -> build/bdist.linux-x86_64/egg/ocnn
copying build/lib.linux-x86_64-3.7/ocnn/__init__.py -> build/bdist.linux-x86_64/egg/ocnn
byte-compiling build/bdist.linux-x86_64/egg/ocnn/transforms.py to transforms.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/octree2voxel.py to octree2voxel.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/octree_conv.py to octree_conv.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/octree2col.py to octree2col.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/ounet.py to ounet.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/octree_interp.py to octree_interp.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/unet.py to unet.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/octree_pool.py to octree_pool.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/resnet.py to resnet.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/lenet.py to lenet.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/octree_pad.py to octree_pad.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/segnet.py to segnet.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/modules.py to modules.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/mlp.py to mlp.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/octree_align.py to octree_align.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ocnn/__init__.py to __init__.cpython-37.pyc
creating stub loader for ocnn/nn.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/ocnn/nn.py to nn.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ocnn.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ocnn.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ocnn.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ocnn.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ocnn.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
ocnn.__pycache__.nn.cpython-37: module references __file__
creating 'dist/ocnn-1.0.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ocnn-1.0.0-py3.7-linux-x86_64.egg
removing '/opt/conda/lib/python3.7/site-packages/ocnn-1.0.0-py3.7-linux-x86_64.egg' (and everything under it)
creating /opt/conda/lib/python3.7/site-packages/ocnn-1.0.0-py3.7-linux-x86_64.egg
Extracting ocnn-1.0.0-py3.7-linux-x86_64.egg to /opt/conda/lib/python3.7/site-packages
ocnn 1.0.0 is already the active version in easy-install.pth

Installed /opt/conda/lib/python3.7/site-packages/ocnn-1.0.0-py3.7-linux-x86_64.egg
Processing dependencies for ocnn==1.0.0
Searching for numpy==1.20.2
Best match: numpy 1.20.2
Adding numpy 1.20.2 to easy-install.pth file
Installing f2py script to /opt/conda/bin
Installing f2py3 script to /opt/conda/bin
Installing f2py3.7 script to /opt/conda/bin

Using /opt/conda/lib/python3.7/site-packages
Searching for torch==1.9.0
Best match: torch 1.9.0
Adding torch 1.9.0 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /opt/conda/bin
Installing convert-onnx-to-caffe2 script to /opt/conda/bin

Using /opt/conda/lib/python3.7/site-packages
Searching for typing-extensions==3.7.4.3
Best match: typing-extensions 3.7.4.3
Adding typing-extensions 3.7.4.3 to easy-install.pth file

Using /opt/conda/lib/python3.7/site-packages
Finished processing dependencies for ocnn==1.0.0
(base) root@(docker)67034be3fb5a:/workspace/ocnn-pytorch
$ python -W ignore test/test_all.py -v
test_backward (test_octree2col.Octree2ColTest) ... ERROR
test_forward (test_octree2col.Octree2ColTest) ...
It's stuck in test_forward for a long time.

**Comment by zhexinXie** [comment]
fixed

**Comment by harris56** [comment]
@zhexinXie May I ask how you fix the test_backward ERROR and stuck in test_forward?
