### ISSUE TITLE
How to use pretrained pytorch O-CNN model in C++?

### ISSUE THREAD

**Issue by MisEty** [microsoft/O-CNN#146]
Hello, I have trained an O-CNN model on pytorch and now I want to save the model and use it in C++. I noticed that the pytorch model can be  converted to Torch Script by torch.jit and use libtorch in C++ to load. But O-CNN operator depend on the octree structure, can I save the pytorch O-CNN model by torch.jit.trace and directly use it in C++?

**Comment by wang-ps** [comment]
Sorry, I could not give you help on this issue.
I have not tried to convert O-CNN to Torch Script, and I have little experience with Torch Script, either.

**Comment by MisEty** [comment]
Thanks. Beside torch script, do you know any other method to use an O-CNN model trained on pytorch in C++ code? Or I have to build the model on caffe O-CNN and train again?

**Comment by wang-ps** [comment]
Using Caffe is a possible solution. 

The C++ definitions of all Pytorch functions can be found in https://github.com/microsoft/O-CNN/blob/master/pytorch/cpp/ocnn.h 
Possibly, these functions can be built for TorchScript.
