### ISSUE TITLE
Inference using my own point cloud on Scannet dataset

### ISSUE THREAD

**Issue by Wavelet303** [microsoft/O-CNN#149]
Hello, first of all congratulations for your incredible work. Currently I have accurately reconstructed indoor scenes using Bundlefusion, obtaining similar results to Scannet's 3D dataset models. In turn, the points clouds are aligned on the axes just like Scannet. How can I make the inference easily on the model using my own point cloud? That is, in what format should you save the data? Is it necessary to make a transformation of this before?
Thanks for your time.

**Comment by wang-ps** [comment]
You can save the point cloud as ply files. Please refer to the tutorial on [ScanNet segmentation](https://github.com/microsoft/O-CNN/blob/master/docs/scannet.md) and relevant code for details, especially the last step in which the network is forwarded to get the predicted segmentation labels.
