### ISSUE TITLE
How long does it take to use ScanNet dataset training model？

### ISSUE THREAD

**Issue by Sun-Wenfeng** [microsoft/O-CNN#150]
I want to know how much computing resources are needed for network training. 
How long does it take to train 600 epoch with 8 GPUs.
Looking forward to your reply，thank you！

**Comment by wang-ps** [comment]
I have not recorded the training time with 8GPUs.
For your reference, the network takes 33 hours when trained with 4 V100 GPUs for 600 epochs. With 8 V100 GPUs, the training time may be 17~20 hours. 
The training log with 4 GPUs can be found [here](https://github.com/microsoft/O-CNN/blob/master/docs/scannet.md).

**Comment by Sun-Wenfeng** [comment]
> I have not recorded the training time with 8GPUs. For your reference, the network takes 33 hours when trained with 4 V100 GPUs for 600 epochs. With 8 V100 GPUs, the training time may be 17~20 hours. The training log with 4 GPUs can be found [here](https://github.com/microsoft/O-CNN/blob/master/docs/scannet.md).

Thank you for your reply.
