### ISSUE TITLE
Understanding about 3D convolution and pool process on octree

### ISSUE THREAD

**Issue by zichunxx** [Microsoft/O-CNN#160]
Hi! 

Thank you for your generous sharing and excellent work. 

Since I am new to octrees, I have some confusion about the 3D convolution and pool processes implemented on octree, which is abstract to me and may be very basic.

After reading [this paper](https://wang-ps.github.io/O-CNN.html), I still can't fully understand the CNN operations on the octree, i.e., 

1) How does the kernel move around the octree? Does it follow the x, y, and z-order like a regular 3D CNN?

2) How to describe the **stride visually** like this? 

<img width="498" alt="stride" src="https://user-images.githubusercontent.com/72594017/201472997-f20de198-28bf-4e84-b05f-0070838b9d4f.png">

3)  If the kernel size needs to match the maximum depth of the octree?

If there is code under the [PyTorch folder ](https://github.com/microsoft/O-CNN/tree/master/pytorch) that can explain these issues, hope you can point it out for me.

Help would be greatly appreciated. 

Thanks!

**Comment by wang-ps** [comment]
O-CNN constrains the CNN storage and computation into non-empty sparse voxels for efficiency and uses the octree data structure to organize and index these sparse voxels.   Currently, this type of 3D convolution is known as Sparse Convolution in the research community. 
The concept of Sparse Convolution is almost the same in our O-CNN in SIGGRAPH 2017, SparseConvNet in CVPR 2018, and MinkowskiNet in CVPR 2019, except that we use Octrees to index sparse non-empty voxel while SparseConvNet and MinowskiNet use Hash Tables.

Here is a [ppt](https://1drv.ms/p/s!Ar9egoTYLACXkCw4HOaEI4P3UG2k?e=fb2A3R) containing animations about O-CNN. Hope it may be helpful to you.

**Comment by zichunxx** [comment]
> O-CNN constrains the CNN storage and computation into non-empty sparse voxels for efficiency and uses the octree data structure to organize and index these sparse voxels. Currently, this type of 3D convolution is known as Sparse Convolution in the research community. The concept of Sparse Convolution is almost the same in our O-CNN in SIGGRAPH 2017, SparseConvNet in CVPR 2018, and MinkowskiNet in CVPR 2019, except that we use Octrees to index sparse non-empty voxel while SparseConvNet and MinowskiNet use Hash Tables.
> 
> Here is a [ppt](https://1drv.ms/p/s!Ar9egoTYLACXkCw4HOaEI4P3UG2k?e=fb2A3R) containing animations about O-CNN. Hope it may be helpful to you.


Thank you for your guidance, I will dive into these references.
