### ISSUE TITLE
"full_layer" variable in Octree.cpp and main.cpp when building octrees

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#17]
Hi, in main.cpp, when building octrees, you initialize the variable int full_layer as:
`int full_layer = 2;`

Does this mean you are actually only getting down to a 2x2x2 voxel resolution for this task?
In other words if I have e.g. a 32x32x32 volume, I would recursively partition into 16x16x16, and then 8x8x8, 4x4x4, then finally 2x2x2. But not 1x1x1?

So if I wanted to do 1x1x1 I would change full_layer = 1, is that correct?

**Comment by wang-ps** [comment]
No.

The octrees of different objects are different. The fully connected layer of neural network requires the dimension of each input should be the same. We use this variable to enforce that the 2nd level of each octree is full. After a series of convolution and pooling, the octree is down-sampled to 2nd level, i.e. to a  4x4x4 volumetric grid. Then the fully connected layer can be used to output the classification probability.
