### ISSUE TITLE
missing "segmentation_5.caffemodel" 

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#18]
Hi, I see caffemodel files for 2 of the tasks but not for the segmentation task:
in O-CNN/caffe/examples/o-cnn/ I see:

M40_5.caffemodel 	release O-CNN version 1.0 	Jun 19, 2017
S55_5.caffemodel 	Add more details about the retrieval experiment 	Aug 23, 2017

but not "segmentation_5.caffemodel" which is used in the test phase command for the segmentation task:
`caffe.exe test --model=segmentation_5.prototxt --weights=segmentation_5.caffemodel --blob_prefix=feature/segmentation_5_test_ --gpu=0 --save_seperately=false --iterations=[...]`
which is described in issue #16:
https://github.com/Microsoft/O-CNN/issues/16
refers to this part of your  README section:
https://github.com/Microsoft/O-CNN#o-cnn-for-shape-segmentation

Do you have an example segmentation_5.caffemodel you could provide?
Thanks.

**Comment by wang-ps** [comment]
Follow the readme, run the experiment and you can get the training result, i.e. the segmentation_5.caffemodel.
This process can also help you to be familiar with the whole pipeline.  :-)
