### ISSUE TITLE
Visualizing part segmentation output without doing CRF

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#19]
For the segmentation task, after running the network in test mode we end up with 2 files:
```
test_labelo.dat
test_prob.dat
```
which are the class labels [segmentation part numbers] and classification probabilities, concatenating together all test examples since uses "save_seperately=false"
They are .dat fomat

In the README:
https://github.com/Microsoft/O-CNN/blob/master/README.md#o-cnn-for-shape-segmentation
you suggest using the CRF code from:
https://github.com/wang-ps/O-CNN/tree/master/densecrf

vs. in issue #11 you also mentioned the function void load_pointcloud() defined in Line 141 in the file octree/Octree/main.cpp. 

If I don't want to do CRF refinement or just want to visualize my unrefined outputs directly that are in the .dat files, do you have an automated tool to visualize this, or do you describe a way of doing this?
Since each of the class labels corresponds to a leaf node of the octree, how do I go from this list of labels in the "labelo.dat" to the 3D model?

Thanks.

**Comment by wang-ps** [comment]
I have upload a tool to convert the octree files to point cloud. 
You can use OpenGL to visualize the point cloud with the output label as the color for each point.
