### ISSUE TITLE
M40_5_segmentation.prototxt  error

### ISSUE THREAD

**Issue by brotherNanNan** [Microsoft/O-CNN#2]
Hi,

Thank you for releasing the code. I am now trying to run M40_5_segmentation.prototxt  . But i encounter a mistake. Here is the error.

I0717 19:12:00.398635 50028 net.cpp:84] Creating Layer derelu3
I0717 19:12:00.399637 50028 net.cpp:406] derelu3 <- deconv3
I0717 19:12:00.400640 50028 net.cpp:367] derelu3 -> deconv3 (in-place)
I0717 19:12:00.401780 50028 net.cpp:122] Setting up derelu3
I0717 19:12:00.402783 50028 net.cpp:129] Top shape: 1 32 8 1 (256)
I0717 19:12:00.402783 50028 net.cpp:137] Memory required for data: 32448
I0717 19:12:00.403786 50028 layer_factory.cpp:58] Creating layer unpool2
I0717 19:12:00.404789 50028 net.cpp:84] Creating Layer unpool2
I0717 19:12:00.405889 50028 net.cpp:406] unpool2 <- deconv3
I0717 19:12:00.405889 50028 net.cpp:406] unpool2 <- pool2_mask
I0717 19:12:00.406893 50028 net.cpp:380] unpool2 -> unpool2
I0717 19:12:00.407896 50028 net.cpp:122] Setting up unpool2
I0717 19:12:00.408897 50028 net.cpp:129] Top shape: 1 32 8 1 (256)
I0717 19:12:00.410903 50028 net.cpp:137] Memory required for data: 33472
I0717 19:12:00.411906 50028 layer_factory.cpp:58] Creating layer deconv4
I0717 19:12:00.411906 50028 net.cpp:84] Creating Layer deconv4
I0717 19:12:00.412909 50028 net.cpp:406] deconv4 <- unpool2
I0717 19:12:00.413911 50028 net.cpp:380] deconv4 -> deconv4
F0717 19:12:00.415916 50028 blob.cpp:32] Check failed: shape[i] >= 0 (-1 vs. 0)

**Comment by wang-ps** [comment]
Sorry, this is my mistake when preparing the file `M40_5_segmentation.prototxt`. I have fixed and updated it. Please pull the latest commit. Thank you for finding this error!

**Comment by brotherNanNan** [comment]
@wang-ps  OK, it works now~
