### ISSUE TITLE
segmentation label output names swapped?

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#20]
re: might be a small issue in saving the outputs:

Thanks for the new commit. After remaking caffe and rerunning the network, using the new command from your readme with the new binary_mode option set to false:
```
caffe.exe test --model=myOctrees.prototxt --weights=myOctrees.caffemodel --gpu=0
  --blob_prefix=feature/myOctrees_test_ --binary_mode=false --save_seperately=true --iterations=[...]
```

I can open my groundtruth and prediction label files and read them. But I think the file names might be reversed; I think predicted<->groundtruth. Just want to check this in case someone uses it in future and it turned out the predictions looked really good only because they were actually the ground truth.

**Comment by wang-ps** [comment]
No.  They are not reversed.
