### ISSUE TITLE
Make runtest fails when building Caffe for OctreeDataBaseLayer

### ISSUE THREAD

**Issue by bensnell** [Microsoft/O-CNN#21]
I've been following the instructions for building Caffe for Ubuntu 16.04 [here](https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide#the-gpu-support-prerequisites). I am successful in running the commands `make all` and `make test`, but hit an error for `sudo make runtest`:

```
[----------] 1 test from LayerFactoryTest/2, where TypeParam = caffe::GPUDevice<float>
[ RUN      ] LayerFactoryTest/2.TestCreateLayer
F0318 05:45:47.677664 22415 db_leveldb.cpp:16] Check failed: status.ok() Failed to open leveldb 
Invalid argument: : does not exist (create_if_missing is false)
*** Check failure stack trace: ***
    @     0x7fddbad735cd  google::LogMessage::Fail()
    @     0x7fddbad75433  google::LogMessage::SendToLog()
    @     0x7fddbad7315b  google::LogMessage::Flush()
    @     0x7fddbad75e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fddb8587cd3  caffe::db::LevelDB::Open()
    @     0x7fddb84a3c91  caffe::OctreeDataBaseLayer<>::OctreeDataBaseLayer()
    @     0x7fddb84a3fb2  caffe::Creator_OctreeDataBaseLayer<>()
    @     0x7fddb8583373  caffe::LayerRegistry<>::CreateLayer()
    @           0x54a54b  caffe::LayerFactoryTest_TestCreateLayer_Test<>::TestBody()
    @           0x8d2a43  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8cc5ca  testing::Test::Run()
    @           0x8cc718  testing::TestInfo::Run()
    @           0x8cc7f5  testing::TestCase::Run()
    @           0x8ccaaf  testing::internal::UnitTestImpl::RunAllTests()
    @           0x8ccde3  testing::UnitTest::Run()
    @           0x465d4d  main
    @     0x7fddb7790830  __libc_start_main
    @           0x46d759  _start
    @              (nil)  (unknown)
Makefile:533: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)
```

If we take a look at the code, the error seems to begin in the file "[test_layer_factory.cpp](https://github.com/BVLC/caffe/blob/6bfc5ca8f7c2a4b7de09dfe7a01cf9d3470d22b3/src/caffe/test/test_layer_factory.cpp#L22-L49)" when the layer being tested is created:
```
layer = LayerRegistry<Dtype>::CreateLayer(layer_param);
```
Even though the OctreeDataBaseLayer is a data layer, it is not identified as such by the tests when the [layer's key is checked](https://github.com/BVLC/caffe/blob/6bfc5ca8f7c2a4b7de09dfe7a01cf9d3470d22b3/src/caffe/test/test_layer_factory.cpp#L33) for a match against the string "Data".

The issue seems to be resolved if this line is modified to read:
```
if (iter->first == "Data" || iter->first == "DataBaseLayer") {
```

**Comment by wang-ps** [comment]
Thank you so much!
I will merge this modification into our code soon.
By the way, I will also release the testcase for our customized octree layer in the near future.
