### ISSUE TITLE
Cannot find output segmentation files

### ISSUE THREAD

**Issue by xiankun1995** [Microsoft/O-CNN#26]
Hello,
I can't find output files in the testing stage. 
My command is this:`"./build/tools/Debug/caffe-d.exe" test --model=examples/o-cnn/segmentation_5.prototxt --weights=seg_5_s2_iter_5000.caffemodel --blob_prefix=feature/segmentation_5_test_ --binary_mode=false --save_seperately=false --iterations=500`
I can run it and screenshot is this: 
![default](https://user-images.githubusercontent.com/37864298/39351305-aba3a9a4-4a33-11e8-936b-e94b8588621e.png)
But there are not output files in my folder. Can you give some suggestions that I can get the output files? Thank you very much!

**Comment by wang-ps** [comment]
According to your command,  you should manually create one folder named as **feature** .
By the way, I notice that you run the caffe in **debug** mode. It is much faster to build and run the code in **release** mode.
