### ISSUE TITLE
 Visualizing output file about segmentation

### ISSUE THREAD

**Issue by xiankun1995** [Microsoft/O-CNN#27]
Hello, thanks for your suggestions about how to get the .dat file yesterday.
I want to visualize this segmentation task result, so I use octree2ply convert the .dat files to point cloud, and this is my command:`Octree2Ply.exe test_label_groundtruth.dat 1`.
But when I run this command, I only get this:
![default](https://user-images.githubusercontent.com/37864298/39395205-5a2e7a64-4b0e-11e8-985c-68204fb901f1.png)
I don't know how to solve it. Can you give me some suggestions again?
Thank you!

**Comment by wang-ps** [comment]
The octree2ply is used to convert the octree file to point cloud, not the test_label_groundtruth.dat file.

**Comment by xiankun1995** [comment]
Oh，I understand...
But how should I use the .dat files?
And what should I do to visualize this segmentation task result?
Thanks a lot!

**Comment by wang-ps** [comment]
You can use an txt viewer to open these files. They are the predicted segmentation labels. And the order to these labels are in correspondence with the point clouds generated via the octree2ply.exe.
To visualize the results,  you can render the point cloud and use the segmentation label as the point cloud color.

The method I provided is just one possible approach to dump the caffe output and visualize the results. There are many other more convenient ways, e.g. via Python.  You can refer to the official tutorial of caffe or search the google.

**Comment by xiankun1995** [comment]
Thank you for helping me so many times.
and when I use txt viewer see the .dat files, I only get this:
![zk1cfdxrr6x1 paw_ 8kivn](https://user-images.githubusercontent.com/37864298/39617174-3bcce824-4fb1-11e8-9a16-0070741adbde.png)
I think it is wrong. could you share me a correct dat file?
Thank you very much!

**Comment by wang-ps** [comment]
I think the reason is that the flag **--save_seperately** is wrongly set as **false**, it should be **true**.

**Comment by xiankun1995** [comment]
Sorry, I want to ask you one more question about the predicted segmentation labels.
I set the flag --save_seperately as true, and I can read the output files by using txt viewer.
In predicted file there are number 0, 1, 2, I think this is predicted segmentation labels. It has three types.
In groundtruth file there are number -1, 0, 1, 3, **I do not know what does -1 mean and the difference between 2 and 3.**
I guess -1 mean no label, could you tell me the answer?
Thank you very much!

**Comment by xiankun1995** [comment]
Hello, I have one problem again. Could you help me:
I think accuracy will be affected if the magnitude of 3d models is too small.
so how many models should I have when I use 3d models with segmentation labels to train ocnn?
Thank you very much.

**Comment by hducg** [comment]
> You can use an txt viewer to open these files. They are the predicted segmentation labels. And the order to these labels are in correspondence with the point clouds generated via the octree2ply.exe.
> To visualize the results, you can render the point cloud and use the segmentation label as the point cloud color.
> 
> The method I provided is just one possible approach to dump the caffe output and visualize the results. There are many other more convenient ways, e.g. via Python. You can refer to the official tutorial of caffe or search the google.

Hi, can I ask a question about the input of octree2ply?

Octree2Ply <filelist> [segmentation]
filelist: a text file of which each line specifies the full path name of a octree file

I was wondering how to create the filelist for octree2ply? I tried to use oct_list_test.txt generated by the data preparation script, but it did not work.

Many thanks.

**Comment by songyadong106** [comment]
@xiankun1995  
I am also doing this work, can I talk with you for a moment? I'd appreciate it if you could.
QQ:2232661644
