### ISSUE TITLE
Caffe revision SHA

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#3]
The README provided suggests a particular caffe revision. It seems this revision is related to Windows Caffe and making Caffe fails on my Ubuntu 16.04 when I copy over the O-CNN files into Caffe and try to make it. 
From your README it says your O-CNN will work on Ubuntu 16.04 as well. Is that correct? I am also using Ubuntu 16.04.
Thanks.

**Comment by wang-ps** [comment]
Could post your error log and the version of you GCC here?

**Comment by wasd12345** [comment]
Hi,

gcc --version:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609


When I use the suggested caffe revision alone, I can compile without errors.
But when I copy over all of the caffe files from the O-CNN repo, and then try to build caffe, I get some errors as attached:
Thanks.

[error_log.txt](https://github.com/Microsoft/O-CNN/files/1419194/error_log.txt)

**Comment by wang-ps** [comment]
It is due to some grammar mistakes in the `octree.cpp`, and I have fixed it. Please pull the least commit.
Note that the experiments in our paper are all done on the Win10, and we have not thoroughly tested the code on the Ubuntu.

**Comment by wasd12345** [comment]
Excellent, successfully compiled on Ubuntu 16.04 after your changes. Thanks.
