### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by xiankun1995** [Microsoft/O-CNN#30]
Hello. I can run the train mode and test mode with the lmdb files you gave in segmentation task.
But the program will stop running when I use my files.
My files is obj format, and I convert it to lmdb format. Then I start train mode but program stop running.
If the data have special requirements in segmentation task?
Please give me some suggestion. Thank you!

**Comment by wang-ps** [comment]
The input of O-CNN is octree files, not obj files. For more details about data preparation, please read our readme.

**Comment by xiankun1995** [comment]
I'm sorry I didn't say it clearly.
I first run the tool `octree.exe` convert my obj files to octree files, and run `convert_octree_data.exe` convert this octree files into a lmdb. Last I run the train mode with the lmdb but the program stop running for a little while.
![h0lh0s 0bfs5 gzzq 17](https://user-images.githubusercontent.com/37864298/41843396-07597f22-78a0-11e8-847b-f1dd5597f503.png)
I can run your lmdb and get the train result. But I fail with my lmdb.

**Comment by wang-ps** [comment]
I could not give you an answer just according to your description. 
I think you can compare the data that we provided (especially the points file we uploaded) and your data, then you should be able to find the reason.

**Comment by xiankun1995** [comment]
Hello, now I know my data are differents with yours.
In your readme, I find there are three parts in your `POINTS` file: 1.dense points 2.normal information 3.correct part annotation. `virtualscanner.exe` can help me with part 1 and 2.
I download the original part annotation data by your link, and I see label and points are separate.
What should I do to input label information into `POINTS` file for completing part 3. Is there a function to read label information in `VirtualScanner.cpp` or other files? 
Thanks!

**Comment by wang-ps** [comment]
Please  refer to the function *load_pointcloud* defined in Line 142 of the .\octree\Octree\main.cpp.

**Comment by xiankun1995** [comment]
The function _load_pointcloud_ can load these *.points information to octree files. I can get the octree files with the segmentation label. 
After I download "A Scalable Active Framework for Region Annotation in 3D Shape Collections", I see points and points_label are separate. What should I do to combine that two types of files and get *.points with segmentation labels like those *.points in your link?
Thanks a lot!

**Comment by CRISZJ** [comment]
> Hello, now I know my data are differents with yours.
> In your readme, I find there are three parts in your `POINTS` file: 1.dense points 2.normal information 3.correct part annotation. `virtualscanner.exe` can help me with part 1 and 2.
> I download the original part annotation data by your link, and I see label and points are separate.
> What should I do to input label information into `POINTS` file for completing part 3. Is there a function to read label information in `VirtualScanner.cpp` or other files?
> Thanks!

Hello, I want to konw how to konw the presentation in the POINTS file. I want to learn the POINTS file ,but  I don't konw how to parse it, could you please help me?
