### ISSUE TITLE
I put this caffe file and build it, I get an error.

### ISSUE THREAD

**Issue by dbsehdudslaz** [Microsoft/O-CNN#32]
I tried to use "convert_octree_date.exe" so I builded caffe with caffe files provided here , I will get the following error:

error : class "caffe::LossParameter" has no member "pre_fixed_normalizer" in smooth_L1_loss_ohem_layer.cu file

The caffe source code I received was from https://github.com/Microsoft/caffe

How can I fix it? I look forward to your reply.

**Comment by wang-ps** [comment]
Our code is based on the official caffe here (https://github.com/BVLC/caffe). 
Please follow the instructions in our Readme to build and run the code.

**Comment by dbsehdudslaz** [comment]
I tried to do that but it can't build. because In this caffe file follow error : 
CMake Error at cmake/WindowsDownloadPrebuiltDependencies.cmake:40 (message):
 Could not find url for MSVC version = 1800 and Python version = 1.4.

I guess this code depend on url https://github.com/willyd/caffe-builder/releases/download

but this url is closed.

**Comment by wang-ps** [comment]
For this issue, please strictly follow the official installation procedure of Windows Caffe in this page ( https://github.com/BVLC/caffe/tree/windows).  After building the Windows Caffe, just download our code, copy and override the original caffe code, and rebuild the code. This is a reliable approach and  I have tested it many times.

Or you can also try the Docker based installation in our Readme.
