### ISSUE TITLE
the evaluation metric of segmentation task

### ISSUE THREAD

**Issue by chengchengxuxu** [Microsoft/O-CNN#33]
Hello,
In order to compare ocnn's performance with others,the evaluation metric is the intersection over union(IoU) of the part class,why don't you use the training accuracy and test accuracy directly?
By the way, could you tell me what's the training accuracy and test accuracy roughly?,I run the converted dataset (02691156),and my training accuracy is 0.91.
And, Is the code for solving IoU just use compared paper's?

Thank you!

**Comment by songyadong106** [comment]
@chengchengxuxu,
I'm also working on this task. Can I talk to you for a moment?  I'd appreciate it if you could QQ:2232661644
