### ISSUE TITLE
Get errors during make: no match for ‘operator=’, must be initialized by constructor, not by ‘{...}’ etc..

### ISSUE THREAD

**Issue by Luckick** [Microsoft/O-CNN#35]
Hi,

After figure out the configuration of dependencies (can install original caffe by make sucsessfully), still get the error in make process. The errors and warnings are showing below. The details are attached in the end.
Can you help me to figure this out?
Thank you for your help!

OS is Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-147-generic x86_64).

**errors include:**
error: in C++98 ‘octree_shape’ must be initialized by constructor, not by ‘{...}’
   vector<int> data_shape, label_shape, octree_shape{ 1 };
                                                        ^
error: no match for ‘operator=’ (operand types are ‘std::vector<int>’ and ‘<brace-enclosed initializer list>’)
 error: converting to ‘const std::vector<int>’ from initializer list would use explicit constructor

**warnings include:** 
warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
   vector<int> data_shape, label_shape, octree_shape{ 1 };
                                        ^
warning: narrowing conversion of ‘((caffe::OctreeDataBaseLayer<float>*)this)->caffe::OctreeDataBaseLayer<float>::batch_size_’

The details are: 
`CXX src/caffe/layers/octree_conv_layer.cpp
In file included from ./include/caffe/layers/octree_conv_layer.hpp:7:0,
                 from src/caffe/layers/octree_conv_layer.cpp:3:
./include/caffe/layers/octree_base_conv_layer.hpp:24:35: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
    const vector<Blob<Dtype>*>& top) override;
                                   ^
In file included from src/caffe/layers/octree_conv_layer.cpp:3:0:
./include/caffe/layers/octree_conv_layer.hpp:25:35: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
    const vector<Blob<Dtype>*>& top) override;
                                   ^
./include/caffe/layers/octree_conv_layer.hpp:30:35: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [enabled by default]
    const vector<Blob<Dtype>*>& top) override;
                                   ^

... 

CXX src/caffe/layers/octree_database_layer.cpp
src/caffe/layers/octree_database_layer.cpp: In member function ‘virtual void caffe::OctreeDataBaseLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
src/caffe/layers/octree_database_layer.cpp:62:40: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
   vector<int> data_shape, label_shape, octree_shape{ 1 };
                                        ^
src/caffe/layers/octree_database_layer.cpp:68:40: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    data_shape = { batch_size_, 3, 8, 1 };
                                        ^
src/caffe/layers/octree_database_layer.cpp:69:32: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    label_shape = { batch_size_ };
                                ^
src/caffe/layers/octree_database_layer.cpp:72:30: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    data_shape = { 1, 3, 8, 1 };
                              ^
src/caffe/layers/octree_database_layer.cpp:73:25: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    label_shape = { 1, 8 };
                         ^
src/caffe/layers/octree_database_layer.cpp: In instantiation of ‘void caffe::OctreeDataBaseLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/octree_database_layer.cpp:271:2:   required from here
src/caffe/layers/octree_database_layer.cpp:62:56: error: in C++98 ‘octree_shape’ must be initialized by constructor, not by ‘{...}’
   vector<int> data_shape, label_shape, octree_shape{ 1 };
                                                        ^
src/caffe/layers/octree_database_layer.cpp:68:15: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    data_shape = { batch_size_, 3, 8, 1 };
               ^
src/caffe/layers/octree_database_layer.cpp:68:15: error: no match for ‘operator=’ (operand types are ‘std::vector<int>’ and ‘<brace-enclosed initializer list>’)
src/caffe/layers/octree_database_layer.cpp:68:15: note: candidate is:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/local/include/boost/thread/pthread/thread_data.hpp:25,
                 from /usr/local/include/boost/thread/thread_only.hpp:17,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from src/caffe/layers/octree_database_layer.cpp:1:
/usr/include/c++/4.8/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = int; _Alloc = std::allocator<int>]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:160:5: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<int>&’
src/caffe/layers/octree_database_layer.cpp:69:16: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    label_shape = { batch_size_ };
                ^
src/caffe/layers/octree_database_layer.cpp:69:16: error: converting to ‘const std::vector<int>’ from initializer list would use explicit constructor ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<int>]’
src/caffe/layers/octree_database_layer.cpp:69:16: warning: narrowing conversion of ‘((caffe::OctreeDataBaseLayer<float>*)this)->caffe::OctreeDataBaseLayer<float>::batch_size_’ from ‘int’ to ‘std::vector<int>::size_type {aka long unsigned int}’ inside { } is ill-formed in C++11 [-Wnarrowing]
src/caffe/layers/octree_database_layer.cpp:72:15: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    data_shape = { 1, 3, 8, 1 };
               ^
src/caffe/layers/octree_database_layer.cpp:72:15: error: no match for ‘operator=’ (operand types are ‘std::vector<int>’ and ‘<brace-enclosed initializer list>’)
src/caffe/layers/octree_database_layer.cpp:72:15: note: candidate is:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/local/include/boost/thread/pthread/thread_data.hpp:25,
                 from /usr/local/include/boost/thread/thread_only.hpp:17,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from src/caffe/layers/octree_database_layer.cpp:1:
/usr/include/c++/4.8/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = int; _Alloc = std::allocator<int>]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:160:5: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<int>&’
src/caffe/layers/octree_database_layer.cpp:73:16: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    label_shape = { 1, 8 };
                ^
src/caffe/layers/octree_database_layer.cpp: In instantiation of ‘void caffe::OctreeDataBaseLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/octree_database_layer.cpp:271:2:   required from here
src/caffe/layers/octree_database_layer.cpp:62:56: error: in C++98 ‘octree_shape’ must be initialized by constructor, not by ‘{...}’
   vector<int> data_shape, label_shape, octree_shape{ 1 };
                                                        ^
src/caffe/layers/octree_database_layer.cpp:68:15: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    data_shape = { batch_size_, 3, 8, 1 };
               ^
src/caffe/layers/octree_database_layer.cpp:68:15: error: no match for ‘operator=’ (operand types are ‘std::vector<int>’ and ‘<brace-enclosed initializer list>’)
src/caffe/layers/octree_database_layer.cpp:68:15: note: candidate is:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/local/include/boost/thread/pthread/thread_data.hpp:25,
                 from /usr/local/include/boost/thread/thread_only.hpp:17,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from src/caffe/layers/octree_database_layer.cpp:1:
/usr/include/c++/4.8/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = int; _Alloc = std::allocator<int>]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:160:5: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<int>&’
src/caffe/layers/octree_database_layer.cpp:69:16: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    label_shape = { batch_size_ };
                ^
src/caffe/layers/octree_database_layer.cpp:69:16: error: converting to ‘const std::vector<int>’ from initializer list would use explicit constructor ‘std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<int>]’
src/caffe/layers/octree_database_layer.cpp:69:16: warning: narrowing conversion of ‘((caffe::OctreeDataBaseLayer<double>*)this)->caffe::OctreeDataBaseLayer<double>::batch_size_’ from ‘int’ to ‘std::vector<int>::size_type {aka long unsigned int}’ inside { } is ill-formed in C++11 [-Wnarrowing]
src/caffe/layers/octree_database_layer.cpp:72:15: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    data_shape = { 1, 3, 8, 1 };
               ^
src/caffe/layers/octree_database_layer.cpp:72:15: error: no match for ‘operator=’ (operand types are ‘std::vector<int>’ and ‘<brace-enclosed initializer list>’)
src/caffe/layers/octree_database_layer.cpp:72:15: note: candidate is:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/local/include/boost/thread/pthread/thread_data.hpp:25,
                 from /usr/local/include/boost/thread/thread_only.hpp:17,
                 from /usr/local/include/boost/thread/thread.hpp:12,
                 from /usr/local/include/boost/thread.hpp:13,
                 from src/caffe/layers/octree_database_layer.cpp:1:
/usr/include/c++/4.8/bits/vector.tcc:160:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = int; _Alloc = std::allocator<int>]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:160:5: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const std::vector<int>&’
src/caffe/layers/octree_database_layer.cpp:73:16: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
    label_shape = { 1, 8 };
                ^
make: *** [.build_release/src/caffe/layers/octree_database_layer.o] Error 1

`

**Comment by wang-ps** [comment]
You should compile the code with c++11 support enabled

**Comment by Luckick** [comment]
> You should compile the code with c++11 support enabled

How should I compile the code with c++11 support enable?
Do you mean something like $(Q)$(CXX) $< -pthread -o $@ $(LINKFLAGS) -std=c++11  in Makefile?

**Comment by wang-ps** [comment]
Sorry that I am not familiar with the Makefile, you can google it. By the way, you should make sure that your compiler supports c++11.


The errors are manily cause by the initialization style from c++11, such as
```cpp 
    vector<int> label_shape = {1, 8};
    vector<int> shape {1, 2, 3, 4}; 
```
   If you can not enable your compiler to support the c++11, you can change them to 
```cpp 
    int tmp1[] = {1, 8}, tmp2[] = {1, 2, 3, 4}; 
    vector<int> label_shape(tmp1, tmp1 + 2);
    vector<int> shape(tmp2, tmp2 + 4);
```

**Comment by Luckick** [comment]
I add add CXXFLAGS += -std=c++11 in Makefile.config, and the previous errors disappear.

However, new error comes in, they may be due to GCC version. 
(I am using gcc (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5)
Could you please share gcc version you are using? 

error details are: 
/usr/include/c++/4.8/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = std::basic_ofstream<char>; _Args = {std::basic_ofstream<char, std::char_traits<char> >}]’:
		/usr/include/c++/4.8/ext/new_allocator.h:120:4: error: use of deleted function ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’
			  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
		/usr/include/c++/4.8/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
		/usr/include/c++/4.8/bits/ios_base.h:792:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
		/usr/include/c++/4.8/bits/basic_ios.h:66:11: error: within this context
		/usr/include/c++/4.8/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<ch                                                                                                                        ar>]’ is private
       			basic_streambuf(const basic_streambuf& __sb)

**Comment by Luckick** [comment]
> I add add CXXFLAGS += -std=c++11 in Makefile.config, and the previous errors disappear.
> 
> However, new error comes in, they may be due to GCC version.
> (I am using gcc (Ubuntu 4.8.5-4ubuntu8~14.04.2) 4.8.5)
> Could you please share gcc version you are using?
> 
> error details are:
> /usr/include/c++/4.8/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = std::basic_ofstream; _Args = {std::basic_ofstream<char, std::char_traits >}]’:
> /usr/include/c++/4.8/ext/new_allocator.h:120:4: error: use of deleted function ‘std::basic_ofstream::basic_ofstream(const std::basic_ofstream&)’
> { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
> /usr/include/c++/4.8/ostream:58:11: error: use of deleted function ‘std::basic_ios::basic_ios(const std::basic_ios&)’
> /usr/include/c++/4.8/bits/ios_base.h:792:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
> /usr/include/c++/4.8/bits/basic_ios.h:66:11: error: within this context
> /usr/include/c++/4.8/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits]’ is private
> basic_streambuf(const basic_streambuf& __sb)

By updating GCC version to 5. Problem solved. (By the way, does not support GCC > 6.)
