### ISSUE TITLE
Docker file fix

### ISSUE THREAD

**Issue by shakes76** [Microsoft/O-CNN#36]
Seems recent [commit in the NCCL library](https://github.com/NVIDIA/nccl/commit/f93fe9bfd94884cec2ba711897222e0df5569a53) broke the docker file. You get the nccl ... make: No rule install error.

I had to edit the docker file by adding 
```
&& git checkout 286916a1a37ca1fe8cd43e280f5c42ec29569fc5
```
to line 62 of the file. This forces the NCCL version to be the version before this commit. The relevant code involving that line now reads
```
RUN git clone https://github.com/BVLC/caffe.git . && git reset --hard $CAFFE_COMMIT && \
    rsync -a $OCNN_ROOT/caffe/ ./ && ex -sc '83i|set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --std=c++11")' -cx CMakeLists.txt && \
    cd python && for req in $(cat requirements.txt) pydot; do pip install $req; done && cd .. && \
    git clone https://github.com/NVIDIA/nccl.git && cd nccl && git checkout 286916a1a37ca1fe8cd43e280f5c42ec29569fc5 && make -j install && cd .. && rm -rf nccl && \
    mkdir build && cd build && \
    cmake -DUSE_CUDNN=1 -DUSE_NCCL=1 .. && \
    make -j"$(nproc)" && \
    mkdir $CAFFE_ROOT/include/caffe/proto && \
    cp $CAFFE_ROOT/build/include/caffe/proto/caffe.pb.h $CAFFE_ROOT/include/caffe/proto/caffe.pb.h
```

**Comment by wang-ps** [comment]
Thank you so much! I will merge your commit in the near release.

**Comment by leeskyed** [comment]
Thank you so much too! Actually I just found this problem and tried to solve myself!
