### ISSUE TITLE
Can number of input channels larger than 3? 

### ISSUE THREAD

**Issue by lrquad** [Microsoft/O-CNN#37]
Hi,

I read the code and does not figure out how to set the number of input channels. For example, if the mesh node has some extra features (maybe another 2x1 vector), how can I embed these features along the 3x1 normal vector (totally 5x1 vector)? So the question is can O-CNN support any num_channels*N*N*N tensor as input?

**Comment by wang-ps** [comment]
The answer is YES. 
And fortunately, I have already implemented this feature. In the next few weeks,  the code will be updated. I will notify you through this issue upon the release. Sorry for the inconvenience.

**Comment by lrquad** [comment]
Thanks very much!

**Comment by Luckick** [comment]
Hi,

What is the usage of displacement? Why do we need this? (I do see slightly change on the shape and the whole object shifts.)
If I don't want to use normal as features. (eg. RGB + others), how should I deal with this revise on coordinates? (Pt[3 * n + m] += normal[3 * n + m] * D;)

Thank you.

**Comment by wang-ps** [comment]
@Luckick The displacement is used to  inflate very thin structures. If the normals of the thin structures fall into one octree node, the average normal might be zero. 

@Luckick @lrquad 
I have released the least code in the pre-release branch. The newest code supports the feature you mentioned.  And I am writing the detailed readme. Currently, use the following code to defined your customized POINTS files.

``` c
Points point_cloud;
// points(3 channels) are required,  labels(1 channel) are optional, 
// and at least one of normal(3 channels) and features(any channels) are required.
vector<float> points, normals, features, labels;
// fill your point infomation into points, normals, features...
point_cloud.set_points(points, normals, features, labels);
// save the points into one binary file.
point_cloud.write_points("my_points.points");
// Then the octree generator can take the saved points file to generate octree
```

**Comment by Luckick** [comment]
It helps a lot! 
Thank you!
