### ISSUE TITLE
.points and .octree format data

### ISSUE THREAD

**Issue by Luckick** [Microsoft/O-CNN#38]
Hi,

Is there any introduction about the format & meaning of .points and .octree format data?

Thank you!

**Comment by wang-ps** [comment]
Currently, one has to read the code to learn the detail about the .points and .octree  format.
I will write more detailed explanation soon.

**Comment by wang-ps** [comment]
Sorry, it is hard for me to explain the implentation in a few words. 
For the data structure, please follow the section 3 of  our O-CNN paper, and some other useful reference can also be find in this section.
