### ISSUE TITLE
question about octree_deconv_layer

### ISSUE THREAD

**Issue by chengchengxuxu** [Microsoft/O-CNN#39]
Hello,I want to ask you for help.
When you do segmentation task, in segmentation_5.prototxt,why the deconv layer's type is OctreeConv,rather than OctreeDeconv?  The question is shown in the figure.
![1540127033 1](https://user-images.githubusercontent.com/43060009/47267334-e766d980-d574-11e8-8700-a958217cfb49.png)

So Is this layer set up by the octree_conv_layer.hpp/cpp/cu ,or set up by the octree_deconv_layer.hpp/cpp/cu?

Thank you!

**Comment by wang-ps** [comment]
When the stride is 1, the conv operation is essentially the same as the deconv operation.

**Comment by chengchengxuxu** [comment]
Got it,thank you!
And I want to ask you one more question,when you write code in windows caffe, how do you debug or just find your mistakes in a efficient way?  
Thank you for your patience and attention.

**Comment by chengchengxuxu** [comment]
Got it!Thank you!
