### ISSUE TITLE
O-CNN net initialization

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#4]
- I'm running your segmentation 5 model with the default parameters.
- I'm using the same data you provided M40_5_2_12  LMDB data [train and test]
- Ubuntu 16.04, From the attached output, you can see it creates layer octreedatabase, loads the LMDB data, starts initializing the network architecture, but then has an issue with the octree_database_layer.

Do you know what is going on here? Thanks.
[ocnn_output_issue.txt](https://github.com/Microsoft/O-CNN/files/1423605/ocnn_output_issue.txt)

**Comment by wang-ps** [comment]
For the segmentation task, you should download the `segmentation.zip`, which contains one lmdb for segmentation.
