### ISSUE TITLE
upgrade_octree

### ISSUE THREAD

**Issue by tangbohu** [Microsoft/O-CNN#47]
I used your provided lmdb, and try to upgrade it.
But I could not find any upgrade_octree_database, however, there is a upgrade_octree.
Thus I adopt it to upgrade the lmdb, but it crashed and said that "bad alloc". 
I am sure my memory is sufficient.

Thus I try to generate the dataset by myself, however, I could find convert_octree_data in Ubuntu.
Could you help me?

**Comment by wang-ps** [comment]
The upgrade_octree_database and convert_octree_data are in the folder containing the executive program caffe. Did you successfully build the caffe?
