### ISSUE TITLE
Can not find executable files "octree2ply" 

### ISSUE THREAD

**Issue by LongruiDong** [Microsoft/O-CNN#51]
Hi,
Following the [1.1   Manual Setup](https://github.com/Microsoft/O-CNN#11--manual-setup) ,I have built successfully Caffe directory 、O-CNN/ocnn/octree and  virtual_scanner, got some executable files like octree、virtualscanner、octree2points...
![image](https://user-images.githubusercontent.com/26404032/50430117-27dc2e00-08fd-11e9-82ed-a59b7b100f61.png)
But I can not find executable files "octree2ply" all the O-CNN/ directory,Can you give me some suggestions again?

**Comment by wang-ps** [comment]
The octree2ply is renamed to octree2mesh. Sorry, I forget to update the readme.
The octree2mesh convert the input octree file into triangle patches, and save the result triangle soup in OBJ format, which can be visualized via the meshlab.
