### ISSUE TITLE
Where is `prepare_dataset.py`?

### ISSUE THREAD

**Issue by ando-takahiro** [Microsoft/O-CNN#54]
Thanks for this nice repository.

I'm finding `prepare_dataset.py` written [here](https://github.com/Microsoft/O-CNN#22--automated-dataset-setup).  I could not find `python folder`.  Any info?

**Comment by wang-ps** [comment]
Yes

**Comment by ando-takahiro** [comment]
I hope someone can update the document some future.  If I learned this script, I would send PR.

Thanks.

**Comment by wang-ps** [comment]
Thank you in advance 👍
