### ISSUE TITLE
caffe.cpp compile question

### ISSUE THREAD

**Issue by wxz1996** [Microsoft/O-CNN#55]
when i complie caffe.cpp in ubuntu16.04 with g++4.8.2, it tell me 

```
/usr/include/c++/4.8.2/bits/stl_construct.h:75:7: error: use of deleted function ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
```
i find in your code is :
`ofstream outfile(filename, std::ios::binary);`

and when i fix it to:
`ofstream outfile;
outfile.open(filename, std::ios::binary);`
it report the same error

**Comment by wang-ps** [comment]
You can make the g++ complier support c++11, and have a try.

**Comment by songyadong106** [comment]
@ wxz1996  
Have you solved the problem yet? I have the same problem.
