### ISSUE TITLE
Data format about Segmentation

### ISSUE THREAD

**Issue by hjwdzh** [Microsoft/O-CNN#56]
In the document, I can see how to prepare the lmdb with <POINT, category>, but how should I prepare the lmdb with <POINT, corresponding semantic labels>?

I notice that the POINT structure incorporates XYZ and normal. Is the RGB information also supported?

**Comment by wang-ps** [comment]
you can include the header points.h(./ocnn/octree/include/octree/points.h) and use the following code to save your own data into a points file: 

```cpp
Points point_cloud;
vector<float> points, normals, features, labels;
// ......
// set your data in points, normals, features, and labels
// points: 3 channels, x_1, y_1, z_1, ..., x_n, y_n, z_n
// normals: 3 channels, nx_1, ny_1, nz_1, ..., nx_n, ny_n, nz_n
// features (such as RGB color): k channels, r_1, g_1, b_1, ..., r_n, g_n, b_n
// labels: 1 channels, per-points labels
// ......
point_cloud.set_points(points, normals, features, labels);
point_cloud.write_points("my_points.points");
// Then the octree generator can take the saved points file to generate octrees
```
