### ISSUE TITLE
octree2mesh

### ISSUE THREAD

**Issue by FredFloopie** [Microsoft/O-CNN#58]
octree2mesh.exe takes parameters "--depth_start"  and "--depth_end".

For the image2shape experiment,  what values should these be set to?  (they are default 0 and 10)

**Comment by wang-ps** [comment]
The default values are OK.

**Comment by FredFloopie** [comment]
Hi,  I would like to try octrees with depth > 7.

I take a .ply model,  and I use ply2points.exe to convert to .points file.
Then I use "octree.exe --adaptive 1 -- adp_depth=2 --depth=10" to convert .points file to .octree.
There is no error message at this point.

Then I use octree2mesh.exe to convert .octree to .obj however I get the message:
"The depth_ should be in range [0, 8]."

Is there a way for me to test higher octree depth?  
Can you elaborate on what the limitation is that doesn't allow depth > 7?
Thanks,

**Comment by wang-ps** [comment]
I have slightly modified the code to make it support octree with depth 8. You can pull the latest code and rebuild the octree2mesh.exe.  
Currently, the maximum  octree depth supported is up to 8. Sorry for the inconvenience. 
We are working to extend the code to support octree with depth larger than 8, but the code is not ready for release now.
