### ISSUE TITLE
Compare 2 octrees

### ISSUE THREAD

**Issue by FredFloopie** [microsoft/O-CNN#59]
Is there already a layer that produces a loss on the difference between 2 already fully formed octrees as input (for example 2 octrees that have been loaded in separate OctreeDatabase layers)?  Or a good fast way to compose layers to do this?  Other than going through  all the octree masks and octree properties and splits etc...?

**Comment by wang-ps** [comment]
The shuffled key of octree can be accessed via the OctreePropertyLayer. According to the shuffled key, the xyz coordinates of each octree node can be calculated (refer to the orignal OCNN paper for details). Then difference of two octree can be got by comparing these octree node coordinates.
