### ISSUE TITLE
building LMBD for shape segmentation task

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#6]
**What tool should I use to build the lmbd database to use in the shape segmentation task?** I am asking because:

For the O-CNN for Shape Segmentation task:
Your network works successfully when I download the zip file "segmentation.zip" which contains the already formatted lmdb.

But if I want to use my own octrees made from using your provided "octree.exe", the README says to run "convert_octree_data.exe".

But looking through the convert_octree_data.cpp code, it says "This script converts the ModelNet dataset to the leveldb/lmdb format used by caffe to perform classification". For the modelnet object classification, there was only 1 label per octree file because a given octree for an object had only 1 classification. But for the segmentation task, every normal vector has labels so the lmdb format would be different right?

**So my question is what tool should I use to build the lmbd database to use in the shape segmentation task and if you can provide it if you have it?**

Thanks.

**Comment by wang-ps** [comment]
The classification label can be set to any value since they will be ignored in the segmentation task.
The segmentation label is contained in the octree files, and our octree_dababase_layer can parse the octree files to get the segmentation label.
