### ISSUE TITLE
Could not use upgrade_points in docker

### ISSUE THREAD

**Issue by ApisXia** [microsoft/O-CNN#62]
I have find a file named upgrade_points in '/workspace/bin'. However, when I try to convert my data, it reports like follow:

root@atara-ZZ:/workspace/bin# upgrade_points --filenames /workspace/dataset/OCNN-Data/segmentation/traininfo.txt --has_label 1
Unknown cmd parameter: --has_label

Usage: update_octree.exe
	 --filenames  <The input filenames>
	[--output_path  <The output path>=.]
	[--verbose  <Output logs>=1]

As if it is update_octree.exe, not upgrade_points.

**Comment by wang-ps** [comment]
I have updated the code and please pull the lastest code to have a try.

**Comment by ApisXia** [comment]
Thank you so much. It works!
By the way, I find that when I use octree to transform the data with segmentation labels, I could not find parameter 'segmentation'. Should I use 'split_label' instead?

**Comment by ApisXia** [comment]
I just find that the 'convert_octree_data' tool could not be found in the docker. Could you upload cmake files? Thanks a lot!

**Comment by wang-ps** [comment]
No. 
If the input point cloud contains segmentation labels, the octree will have labels, too.
