### ISSUE TITLE
tf branch README

### ISSUE THREAD

**Issue by tianyudwang** [microsoft/O-CNN#65]
What is the data preparation, training and testing commands for the tensorflow implementation? It seems that the README is still referring to the caffe training and testing.

**Comment by CRISZJ** [comment]
I also have the same question. Could you please tell us how to ues the code based on the tensorflow framework

**Comment by wang-ps** [comment]
I will update the readme soon.

**Comment by wang-ps** [comment]
@CRISZJ @tianyudwang 
Sorry for the delay. I have updated the readme and tested the tensorflow code just now.
Now you can follow the [installation](https://github.com/microsoft/O-CNN/blob/master/docs/installation.md) guide and [shape classafication](https://github.com/microsoft/O-CNN/blob/master/docs/classification.md) guide to have a try.

**Comment by CRISZJ** [comment]
> @CRISZJ @tianyudwang
> Sorry for the delay. I have updated the readme and tested the tensorflow code just now.
> Now you can follow the [installation](https://github.com/microsoft/O-CNN/blob/master/docs/installation.md) guide and [shape classafication](https://github.com/microsoft/O-CNN/blob/master/docs/classification.md) guide to have a try.

thanks. I will try later.
