### ISSUE TITLE
prepare_dataset.py is missing?

### ISSUE THREAD

**Issue by kamiry** [microsoft/O-CNN#67]
Hello, I don't find the prepare_dataset.py file. Can you provide it again? Thanks.

**Comment by wang-ps** [comment]
Do you mean this file [`O-CNN/examples/generate_dataset.py`](https://github.com/microsoft/O-CNN/blob/master/examples/generate_dataset.py)?

**Comment by kamiry** [comment]
> Do you mean this file [`O-CNN/examples/generate_dataset.py`](https://github.com/microsoft/O-CNN/blob/master/examples/generate_dataset.py)?

No, I don't think it is generate_dataset.py. In your readme, you mentioned that you have an Automated Dataset Setup (For Ubuntu only). Its parameters look like the following, for doing the whole conversion process from ModelNet to lmdb. I want refer to this .py to confirm I am doing the right conversion process.
Usage: 
    prepare_dataset.py [-h] --datadir DATADIR --dataset {ModelNet10,ModelNet40}
        --points_converter_path POINTS_CONVERTER_PATH
        --octree_converter_path OCTREE_CONVERTER_PATH
        --lmdb_converter_path LMDB_CONVERTER_PATH
...

**Comment by CRISZJ** [comment]
Do you solve it and I have the same problem. And when  I convert point to octree , each point will product 11 octree,  do you meet this problem?

**Comment by CRISZJ** [comment]
I find that the file of generate_dataset.py is the file that author mentioned. But  there is no moudle called ocnn

**Comment by kamiry** [comment]
> Do you solve it and I have the same problem. And when I convert point to octree , each point will product 11 octree, do you meet this problem?

In author's original paper, it said: "We augment the dataset by rotating each model along the upright direction uniformly to generate 12 poses for each model." I think that is why their code produced 12 octree files from one .point file.

**Comment by CRISZJ** [comment]
> > Do you solve it and I have the same problem. And when I convert point to octree , each point will product 11 octree, do you meet this problem?
> 
> In author's original paper, it said: "We augment the dataset by rotating each model along the upright direction uniformly to generate 12 poses for each model." I think that is why their code produced 12 octree files from one .point file.

Thanks

**Comment by wang-ps** [comment]
It is deleted, I have updated the readme.
