### ISSUE TITLE
About building caffe

### ISSUE THREAD

**Issue by CRISZJ** [microsoft/O-CNN#69]
I have succeeded in building Caffe with revision 6bfc5ca (make all ),then I download O-CNN and copy the code in the directory O-CNN/caffe into the caffe directory to override the original Caffe code, and i also build it successfully. But when i run the make test, i meet the problem:

Makefile:587: recipe for target '.build_release/src/caffe/test/test_octree.o' failed
make: *** [.build_release/src/caffe/test/test_octree.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by wang-ps** [comment]
You can ignore it, and do the experiments directly. 
The code for unit tests is only tested on the windows platform, and I have not checked it on Ubuntu.

**Comment by CRISZJ** [comment]
Thanks for your reply,and when I convert the .points file to .octree file, I use the command of ./octree --filenames filelist.txt --depth 5 --axis z . And I find one .point file will product 11 .octree file and I want to konw whether it is right?

**Comment by wang-ps** [comment]
The executive file `octree` accepts one command line parameter `--rot_num`, whose  default value is 12. So give one input point cloud, 12 octree will be generated. If you set `--rot_num 1`, only one octree  is generated.

**Comment by CRISZJ** [comment]
OK,Thanks
