### ISSUE TITLE
octree files

### ISSUE THREAD

**Issue by gk2500** [Microsoft/O-CNN#7]
Thanks for providing links to download the lmbd data to repeat some of your examples, like the segmentation task.
Any chance you could also share a few example octree files on their own [not in the lmbd format]?
Thanks.

**Comment by wang-ps** [comment]
Sure.  Attached.

[octree_example.zip](https://github.com/Microsoft/O-CNN/files/1436479/octree_example.zip)

**Comment by wasd12345** [comment]
Thanks, do you have a standard way of reading these binary files to view the contents?

**Comment by wang-ps** [comment]
Read the code in the octree.cpp or octree_database_layer.cpp, where there are functions that show how to parse the octree files.
