### ISSUE TITLE
about octree_database_layer.cpp

### ISSUE THREAD

**Issue by lujian001** [microsoft/O-CNN#70]
Through reading the paper and related materials, I don't understand the following settings. For each octree file code input network, use blob {1, signal_channel_8, 1}. How should I explain it here?
`// initialize top blob shape
  // a workaround for a valid first-time reshape
  vector<int> data_shape{ 1, signal_channel_, 8, 1 };
  top[0]->Reshape(data_shape);`

**Comment by wang-ps** [comment]
The shape of each blob is {1, `signal_channal`, `octree_node_number`, 1}.
The `octree_node_number` is varied for different octrees. In the first-time initialization, I just set it as 8. At  runtime, it will be the actual node number of the octree.

**Comment by lujian001** [comment]
Thank you very much for your reply, which solved the doubts that have been bothering me for a long time.
