### ISSUE TITLE
About tensorflow code

### ISSUE THREAD

**Issue by CRISZJ** [microsoft/O-CNN#71]
Thanks for your code.When I use the code basis tensorflow, I run the file of build.py. I meet some problems as :
g++ -std=c++11 -O2 -shared -o libocnn.so object/*.o -I/home/onefivechen/anaconda3/envs/ocnn/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -I../../octree/octree -I /usr/local/cuda-10.0/include -L /usr/local/cuda-10.0/lib64 -D GOOGLE_CUDA=1 -L/home/onefivechen/anaconda3/envs/ocnn/lib/python3.6/site-packages/tensorflow -l:libtensorflow_framework.so.1 -L../../octree/build -loctree_lib -lrply -fPIC -lcudart
/usr/bin/ld: cannot find -loctree_lib
/usr/bin/ld: cannot find -lrply
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'libocnn.so' failed
make: *** [libocnn.so] Error 1

Could you please tell me what environment do the code need?
I use python3.6 cuda10.0 and tensorflow-gpu14.0

**Comment by CRISZJ** [comment]
it is may be  the wrong version of the numpy

**Comment by CRISZJ** [comment]
This seems to be missing some files. octree_lib? ocnn.so? rply?

**Comment by wang-ps** [comment]
I have updated the readme. You can follow the instructions to build the code.

**Comment by CRISZJ** [comment]
After cmake, I meet some problems:

/home/onefivechen/Desktop/O-CNN-tf/octree/octree/math_functions.cpp: In function ‘void bounding_sphere(float&, float*, const float*, int)’:
/home/onefivechen/Desktop/O-CNN-tf/octree/octree/math_functions.cpp:19:3: error: ‘Miniball’ has not been declared
   Miniball::Miniball<Miniball::CoordAccessor<PointIterator, CoordIterator> >
   ^
/home/onefivechen/Desktop/O-CNN-tf/octree/octree/math_functions.cpp:19:22: error: ‘Miniball’ has not been declared
   Miniball::Miniball<Miniball::CoordAccessor<PointIterator, CoordIterator> >
                      ^
/home/onefivechen/Desktop/O-CNN-tf/octree/octree/math_functions.cpp:19:59: error: expected primary-expression before ‘,’ token
   Miniball::Miniball<Miniball::CoordAccessor<PointIterator, CoordIterator> >
                                                           ^
/home/onefivechen/Desktop/O-CNN-tf/octree/octree/math_functions.cpp:19:74: error: expected primary-expression before ‘>’ token
   Miniball::Miniball<Miniball::CoordAccessor<PointIterator, CoordIterator> >
                                                                          ^
/home/onefivechen/Desktop/O-CNN-tf/octree/octree/math_functions.cpp:19:76: error: expected primary-expression before ‘>’ token
   Miniball::Miniball<Miniball::CoordAccessor<PointIterator, CoordIterator> >
                                                                            ^
/home/onefivechen/Desktop/O-CNN-tf/octree/octree/math_functions.cpp:20:29: error: ‘miniball’ was not declared in this scope
   miniball(dim, ap, ap + npt);
                             ^
CMakeFiles/octree_lib.dir/build.make:114: recipe for target 'CMakeFiles/octree_lib.dir/octree/math_functions.cpp.o' failed
make[2]: *** [CMakeFiles/octree_lib.dir/octree/math_functions.cpp.o] Error 1
CMakeFiles/Makefile2:371: recipe for target 'CMakeFiles/octree_lib.dir/all' failed
make[1]: *** [CMakeFiles/octree_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Do you konw how to solve it?

**Comment by CRISZJ** [comment]
I found that there is no file called Miniball.hpp in the octree. And I also find it in folder external, but is is an empty file. Are you missing it?

**Comment by CRISZJ** [comment]
solve it

**Comment by zhDai** [comment]
> Thanks for your code.When I use the code basis tensorflow, I run the file of build.py. I meet some problems as :
> g++ -std=c++11 -O2 -shared -o libocnn.so object/*.o -I/home/onefivechen/anaconda3/envs/ocnn/lib/python3.6/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -I../../octree/octree -I /usr/local/cuda-10.0/include -L /usr/local/cuda-10.0/lib64 -D GOOGLE_CUDA=1 -L/home/onefivechen/anaconda3/envs/ocnn/lib/python3.6/site-packages/tensorflow -l:libtensorflow_framework.so.1 -L../../octree/build -loctree_lib -lrply -fPIC -lcudart
> /usr/bin/ld: cannot find -loctree_lib
> /usr/bin/ld: cannot find -lrply
> collect2: error: ld returned 1 exit status
> Makefile:22: recipe for target 'libocnn.so' failed
> make: *** [libocnn.so] Error 1
> 
> Could you please tell me what environment do the code need?
> I use python3.6 cuda10.0 and tensorflow-gpu14.0

How do u solve it？
