### ISSUE TITLE
about points.h

### ISSUE THREAD

**Issue by lujian001** [microsoft/O-CNN#73]
`enum PropType { kPoint = 1, kNormal = 2, kFeature = 4, kLabel = 8 };`
Is there anything special about the numbers above?
If I add two parameters similar to features, can the following settings be used?
`enum PropType { kPoint = 1, kNormal = 2, kFeature = 4, KFeature1=5,KFeature2=6,kLabel = 8 }`
Looking forward to reply, thank you very much!

**Comment by wang-ps** [comment]
No, your modification will not work.
You should take care of all the functions that use PropType .

**Comment by lujian001** [comment]
thank you for your reply！
I changed the following settings and recompiled successfully.Does it mean this is feasible?
`enum PropType { kPoint = 1, kNormal = 2, kFeature = 4, KFeature1=8,KFeature2=16,kLabel = 32 }`

**Comment by lujian001** [comment]
It works,By imitating the organization of feartures and expanding two more, I successfully generated points files and octree files.Next, perform octree file conversion to lmdb file.
