### ISSUE TITLE
tf branch questions

### ISSUE THREAD

**Issue by chenming-wu** [microsoft/O-CNN#74]
Hi Peng-Shuai,

I encountered two problems during using O-CNN tensorflow branch:

 * there is a `points_database = _tf_ocnn_module.points_database # todo: delete this operator` in `/tensorflow/libs/__init__.py`, is that ok to delete this line? otherwise I cannot compile the lib.
* in `/tensorflow/script/cls.py`, it uses `points_dataset` in `train_network` function while the dataset is `octree_dataset` in `test_network`, is that correct or a typo?

Thanks!

**Comment by CRISZJ** [comment]
> Hi Peng-Shuai,
> 
> I encountered two problems during using O-CNN tensorflow branch:
> 
> * there is a `points_database = _tf_ocnn_module.points_database # todo: delete this operator` in `/tensorflow/libs/__init__.py`, is that ok to delete this line? otherwise I cannot compile the lib.
> * in `/tensorflow/script/cls.py`, it uses `points_dataset` in `train_network` function while the dataset is `octree_dataset` in `test_network`, is that correct or a typo?
> 
> Thanks!

hi,what's your problem, I also have some problems, it is as  follows:

/home/user/anaconda3/envs/ocnn/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libocnn.so: undefined symbol: _ZNK10PointsInfo12check_formatERSs

Did you have the same problem?

**Comment by chenming-wu** [comment]
> > Hi Peng-Shuai,
> > I encountered two problems during using O-CNN tensorflow branch:
> > 
> > * there is a `points_database = _tf_ocnn_module.points_database # todo: delete this operator` in `/tensorflow/libs/__init__.py`, is that ok to delete this line? otherwise I cannot compile the lib.
> > * in `/tensorflow/script/cls.py`, it uses `points_dataset` in `train_network` function while the dataset is `octree_dataset` in `test_network`, is that correct or a typo?
> > 
> > Thanks!
> 
> hi,what's your problem, I also have some problems, it is as follows:
> 
> /home/user/anaconda3/envs/ocnn/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
> lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: libocnn.so: undefined symbol: _ZNK10PointsInfo12check_formatERSs
> 
> Did you have the same problem?

Sorry, I don't have this problem. Maybe you could try to clean your built files and rebuild again.

**Comment by CRISZJ** [comment]
> > > Hi Peng-Shuai,
> > > I encountered two problems during using O-CNN tensorflow branch:
> > > 
> > > * there is a `points_database = _tf_ocnn_module.points_database # todo: delete this operator` in `/tensorflow/libs/__init__.py`, is that ok to delete this line? otherwise I cannot compile the lib.
> > > * in `/tensorflow/script/cls.py`, it uses `points_dataset` in `train_network` function while the dataset is `octree_dataset` in `test_network`, is that correct or a typo?
> > > 
> > > Thanks!
> > 
> > 
> > hi,what's your problem, I also have some problems, it is as follows:
> > /home/user/anaconda3/envs/ocnn/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
> > lib_handle = py_tf.TF_LoadLibrary(library_filename)
> > tensorflow.python.framework.errors_impl.NotFoundError: libocnn.so: undefined symbol: _ZNK10PointsInfo12check_formatERSs
> > Did you have the same problem?
> 
> Sorry, I don't have this problem. Maybe you could try to clean your built files and rebuild again.

Thanks for your reply, I try to rebuild it , but is is not success. When you follow the author' readme, have you meeting this warning?

octree/octree/octree_nn.cu(329): warning: expression has no effect
octree/octree/octree_nn.cu(358): warning: expression has no effect
octree/octree/octree_nn.cu(383): warning: expression has no effect

**Comment by wang-ps** [comment]
@CRISZJ  The warnings can be safely ignored. 
Your problem on `undefined symbol: _ZNK10PointsInfo12check_formatERSs` is caused by the incompatible GCC version you used to complie the code.
Please **EXACTLY** follow the readme to build the code, if you still have problems, let me know.

**Comment by CRISZJ** [comment]
> @CRISZJ The warnings can be safely ignored.
> Your problem on `undefined symbol: _ZNK10PointsInfo12check_formatERSs` is caused by the incompatible GCC version you used to complie the code.
> Please **EXACTLY** follow the readme to build the code, if you still have problems, let me know.
Thanks for your reply. The version of gcc in my computer is 5.4.0. Is that right?  I also follow the reademe to build anthoer enviroments.

**Comment by wang-ps** [comment]
Do you install tensorflow via the following command: `conda create -n tf-1.14.0 tensorflow-gpu==1.14.0`

**Comment by CRISZJ** [comment]
> Do you install tensorflow via the following command: `conda create -n tf-1.14.0 tensorflow-gpu==1.14.0`

Sure , I also use the virtual enviroments

**Comment by iDzh** [comment]
May I ask if anyone has run the code through?

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/76673052-b4473f00-65dc-11ea-87f1-20fd9bc3093d.png)

Hello, I would like to ask you to follow your steps but can't get the label, can you help me to see it?The data set I'm using is A

**Comment by songyadong106** [comment]
@chenming-wu  @CRISZJ  @wang-ps  @iDzh   
can you help me to see it?

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/76673113-3c2d4900-65dd-11ea-8e88-0ca6b953be79.png)

Hello, I would like to ask you to follow your steps but can't get the label, can you help me to see it?The segmentation data of "02691156",thanks!

**Comment by songyadong106** [comment]
@chenming-wu @CRISZJ @wang-ps @iDzh
can you help me to see it?

**Comment by wang-ps** [comment]
@chenming-wu @songyadong106 
Sorry for the delay. I have updated the readme and tested the tensorflow code just now.
Now you can follow the [installation](https://github.com/microsoft/O-CNN/blob/master/docs/installation.md) guide and [shape classafication](https://github.com/microsoft/O-CNN/blob/master/docs/classification.md) guide to have a try.
