### ISSUE TITLE
tf branch: Points class has no info() method.

### ISSUE THREAD

**Issue by Luckick** [microsoft/O-CNN#77]
Hi,

In O-CNN/octree/tools/build_octree.cpp line 48: 
`succ = point_cloud_.info().check_format(msg);`
and point_cloud_ is `Points point_cloud_;` according to line 103.

However, for Points class, in O-CNN/octree/octree/points.h, info() is not provided.
How can I fix this?

Thanks.

**Comment by wang-ps** [comment]
@Luckick 
Sorry for the delay. I have updated the readme and tested the tensorflow code just now.
Now you can follow the [installation](https://github.com/microsoft/O-CNN/blob/master/docs/installation.md) guide and [shape classafication](https://github.com/microsoft/O-CNN/blob/master/docs/classification.md) guide to have a try.
