### ISSUE TITLE
Data for segmentation

### ISSUE THREAD

**Issue by songyadong106** [microsoft/O-CNN#79]
I wonder which one is the file of  you mentioned(the dense point clouds with segmentation labels)
![image](https://user-images.githubusercontent.com/49023424/76378723-2293c380-6389-11ea-948a-564a251498ea.png)

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/76378794-5969d980-6389-11ea-966a-413fc988d277.png)

I want to ask you whether there are labels in these two files?

**Comment by songyadong106** [comment]
![image](https://user-images.githubusercontent.com/49023424/76379657-a949a000-638b-11ea-9bb4-dbf6ee577cb2.png)

This parameter of "segmention = 1" is not in "octree.exe"

**Comment by songyadong106** [comment]
This parameter of "segmention = 1" is not in "octree.exe"
![image](https://user-images.githubusercontent.com/49023424/76379794-14937200-638c-11ea-8073-3ff6fc312076.png)

**Comment by wang-ps** [comment]
1. The segmentation.zip is a lmbd database, which can be directly used by caffe.  
2. The zip files, like 04379243.zip, contain raw point files.
3. Ignore the segmentation parameter. I will update the readme soon.

**Comment by songyadong106** [comment]
很感谢您光速的回复，但是我现在想用tensorflow版本，也就是说我不能直接用lmbd 格式，我需要原始点云加标签的数据集，然后按照你的readme 去运行，然后在运行octree.exe时会产生带有标签的octree file ,但是现在没有也就是说我用的点云文件里面是没有标签的，是这样吗？ 如果是这样您这边有带有标签的点云吗？&nbsp; 我看readme里面说的是有的你？&nbsp; 谢谢！






----------&nbsp;原始邮件&nbsp;------------------


发件人:&nbsp;"Peng-Shuai Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月14日(星期六) 上午10:40
收件人:&nbsp;"microsoft/O-CNN"<O-CNN@noreply.github.com&gt;;
抄送:&nbsp;"可爱男孩"<2232661644@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/O-CNN] Data for segmentation (#79)





  
The segmentation.zip is a lmbd database, which can be directly used by caffe.
 
The zip files, like 04379243.zip, contain raw point files.
 
Ignore the segmentation parameter. I will update the readme soon.
