### ISSUE TITLE
OctreePaddingLayer

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#8]
In the octree_base_conv_layer.cpp, there is a TODO item, OctreePaddingLayer where it says "The OctreePaddingLayer should be added before "

Is this related to using non-power of 2 input dimensions? Will your net work for volumes with non-power of 2 dimensions?

**Comment by wang-ps** [comment]
Theoretically, it is possible to use input with non-power of 2 input dimensions (perhaps it will be supported in the future).
But, for now, the dimension of the input has to be the power of 2.
