### ISSUE TITLE
Update Tensorflow

### ISSUE THREAD

**Issue by songyadong106** [microsoft/O-CNN#82]
![image](https://user-images.githubusercontent.com/49023424/77038545-fd3d3000-69ee-11ea-9122-d92971a4cda3.png)

can you help me?

**Comment by wang-ps** [comment]
The error message indicates that the PyBind can not be found. Do you build the code according to the instructions strictly?

**Comment by songyadong106** [comment]
thanks,I followed your method several times and found that it worked successfully
