### ISSUE TITLE
Validate the model

### ISSUE THREAD

**Issue by eric85810** [microsoft/O-CNN#83]
Hello, would you like to ask how do you perform a verification test on the trained model and what kind of file is the test, is it .off or .points, or an octree file?
I want to use your model for pre-train, but I have the following problem：

Cannot copy param 0 weights from layer 'ip2'; shape mismatch. Source param shape is 40 128 (5120); target param shape is 5 128 (640). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.

你好，想请问您如何对训练好的模型进行验证测试，测试的档案类别为何，是.off还是.points，或是octree档

**Comment by wang-ps** [comment]
1. Run the following command to test:
    ```
    python run_cls.py configs/cls_octree_test.yaml
    ```
2. For the problem `Cannot copy param 0 weights from layer 'ip2'; shape mismatch. Source param shape is 40 128 ...` ,  the reason is that when training on ModelNet40, the dimension of the last  FC is 40x128 for the 40-category classification, but the FC of your network is  5x128 for the 4-category classification.  So you have to rename the layer's parameters to train it from scratch. 

3. 测试的时候数据处理跟训练一样，需要将.off转换为.points或者.octree

**Comment by eric85810** [comment]
Suppose I have a model file of an aircraft to use
ocnn_M40_5.caffemodel to test his accuracy, how can I use the command
line, thank you

抱歉打扰您，由于我是初学者，想问您如何加载自己的.points档去让已训练好的模型分辨，command
line如何下，因为在网上查询的多是图片辨识，都要有个均值档跟deploy.prototxt才能进行分辨，谢谢您我可能说的不够明确，我举个例子，假设我有一个飞机的模型档要用ocnn_M40_5.caffemodel，来测试他的准确性，那我要如何下command
line,谢谢




Peng-Shuai Wang <notifications@github.com>於 2020年3月25日 週三，下午7:48寫道：

**Comment by eric85810** [comment]
您好
  不好意思又打扰您
  在阅读您的文献时有些问题，不知道您方不方便为我解惑，在o-cnn中，不同的模型以八叉树做切割，那假设今天有两个同样是飞机模型，有可能切
下去的相同位置在这两个模型上是不同位置，想请问这样要如何辨识他是飞机模型，假设一个飞机头的座标与另一个正好相反之类的情况。
  谢谢您

Peng-Shuai Wang <notifications@github.com>於 2020年3月26日 週四，下午9:33寫道：

**Comment by chenteng1998** [comment]
您好
当运行以下命令进行测试时：python run_cls.py configs/cls_octree_test.yaml 
得到如下反馈
Traceback (most recent call last):
  File "run_cls.py", line 41, in <module>
    FLAGS = parse_args()
  File "O-CNN-master/tensorflow/script/config.py", line 139, in parse_args
    _update_config(FLAGS, args)
  File "O-CNN-master/tensorflow/script/config.py", line 108, in _update_config
    FLAGS.merge_from_list(args.opts)
  File "anaconda3/envs/tensorflow/lib/python3.7/site-packages/yacs/config.py", line 226, in merge_from_list
    cfg_list
  File "anaconda3/envs/tensorflow/lib/python3.7/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['configs/cls_octree_test.yaml']; it must be a list of pairs
请问该如何解决 谢谢！

**Comment by wang-ps** [comment]
@chenteng1998  你运行的命令缺少关键字`--config`, 运行如下命令试一试：`python run_cls.py --config configs/cls_octree_test.yaml`

**Comment by chenteng1998** [comment]
> @ chenteng1998 你运行的命令关键字`--config`，运行如下命令试一试：
> 
> ```
> python run_cls.py --config configs/cls_octree_test.yaml
> ```

谢谢！！我的问题已经解决
