### ISSUE TITLE
关于验证已训练好的模型

### ISSUE THREAD

**Issue by eric85810** [microsoft/O-CNN#85]
抱歉打扰您，由于我是初学者，想问您如何加载自己的.points档去让已训练好的模型分辨，command line如何下，因为在网上查询的多是图片辨识，都要有个均值档跟deploy.prototxt才能进行分辨，谢谢您

**Comment by eric85810** [comment]
抱歉，我可能说的不够明确，我举个例子，假设我有一个飞机的模型档要用ocnn_M40_5.caffemodel，来测试他的准确性，那我要如何下command line,谢谢

**Comment by wang-ps** [comment]
命令如下。
```
  caffe test --model=ocnn_m40_5.prototxt  --gpu=0 --weights=models/ocnn_M40_5.caffemodel --iterations=10
```
注意修改ocnn_m40_5.prototxt里的第31行，改成你的lmdb数据库的位置。另外上面这个命令迭代次数为10次，prototxt里的batch_size为32，相当于测试了320个数据。
关于caffe的使用请参考官方教程：http://caffe.berkeleyvision.org/tutorial/interfaces.html

**Comment by eric85810** [comment]
您好，如果我的测试档只有一个3d模型，也是要将其转为lmdb吗，谢谢，很抱歉一直打扰。

Peng-Shuai Wang <notifications@github.com>於 2020年3月26日 週四，下午9:32寫道：

**Comment by eric85810** [comment]
您好，我想表达的意思是，若我只有一个.off，我想将他利用model来辨识是在哪一类也是要将其转为lmdb并丢入吗，由于我的资料只有一个，所以batchsize是要调为1吗，谢谢！

黃仲誼 <eric85810@gmail.com>於 2020年3月26日 週四，下午10:00寫道：

**Comment by wang-ps** [comment]
是的，目前只支持这个流程。TensorFlow的代码更灵活，支持在python中读取单个模型，不必转为数据库文件。

**Comment by eric85810** [comment]
好的，感谢您耐心回覆，想问您当我只改batchsize时都会出现错误，想请问是什么原因呢，再次谢谢您。

Peng-Shuai Wang <notifications@github.com>於 2020年3月27日 週五，上午10:56寫道：

**Comment by wang-ps** [comment]
改动batch_size不应该出错，我们自己的实验中，多次改动过这个参数。我才应该是你的数据的问题。

**Comment by eric85810** [comment]
您好，但我将batch_size改为1后会出现以下erro message
 bottom[0]->shape(0) == bottom[1]->shape(0) (32 vs. 1) The data and label
should have the same first dimension.




Peng-Shuai Wang <notifications@github.com> 於 2020年3月27日 週五 下午9:01寫道：
