### ISSUE TITLE
Octree::octree2mesh() bug on ubuntu 18.04

### ISSUE THREAD

**Issue by jeichelbaum** [microsoft/O-CNN#87]
Issue: abs(x) returns 0 for x in range [0, 1[ on Ubuntu 18.04 gcc. This results in a buggy octree2mesh conversion and has possible other bugs, which I didn't notice so far. As a fix you could use the fabs(x) from the already included library <cmath>. I can submit a Pull Request if you want.

Best
Jeri

**Comment by wang-ps** [comment]
Thank you for pointing out this issue. Your pull request is welcomed.

**Comment by wang-ps** [comment]
I have fixed this issue just now.  
This is a serious problem, which may affect the `octree2mesh` and `adaptive_octree`.
