### ISSUE TITLE
curr_depth_

### ISSUE THREAD

**Issue by wasd12345** [Microsoft/O-CNN#9]
Hi,

I noticed your commit message says something about setting curr_depth_ manually. Where should I do that? Is it related to the following error I'm getting:

`F1128 12:35:09.046485  2298 octree_base_conv_layer.cpp:158] Check failed: bottom_h == octree_batch_.node_num(curr_depth_) (199936 vs. 40448) The OctreePaddingLayer should be added before conv1`

I'm getting this error related to the octree padding layer and number of octree nodes, despite using power of 2 cube dimensions (I'm using 64^3 volumes):

Thanks.

**Comment by wang-ps** [comment]
Take the prototxt I provided as an example. For every layer related with octree, the `curr_depth` in the `octree_param` should be set manually.

......
```
layer {
  name: "conv1"
  type: "OctreeConv"
  bottom: "data"
  top: "conv1"
  convolution_param {
   ......
  }
  **octree_param {
    curr_depth: 5
  }**
}
```
......
