### ISSUE TITLE
points2ply not working

### ISSUE THREAD

**Issue by ebartrum** [microsoft/O-CNN#90]
After installation, I tried to run points2ply as follows:

./points2ply --filenames <path>/model.points --output_path <path>/02691156-ply/

This was printed to the terminal:
Processing: <=P=P=P><'=>w=P>B=P>]P >Bq<P(>
Segmentation fault (core dumped)

And the output dir now contains a file with name:
'<='$'\322\320''P'$'\277\342\340\340''='$'\004\364''7='$'\322\320''P'$'\277\362\360\360''='$'\361\270''3='$'\322\320''P'$'\277\201\200'

Any idea how I can fix this?
Thanks

**Comment by wang-ps** [comment]
Following the  `--filenames` is the filename of a txt file which contains the absolute path of the points files.
