### ISSUE TITLE
caffe/experiments/prepare_dataset.py bug on line 163

### ISSUE THREAD

**Issue by lcflyr** [microsoft/O-CNN#94]
I run the python prepare_dataset.py --run=m40_generate_ocnn_lmdb ^
                          --octree=<The path of the octree> ^
                          --converter=<The path of the convert_octree_data>

Reult the :

Traceback (most recent call last):
  File "prepare_dataset.py", line 244, in <module>
    m40_generate_ocnn_lmdb(depth=5)
  File "prepare_dataset.py", line 163, in m40_generate_ocnn_lmdb
    shuffle = '--shuffle' if shuffle else '--noshuffle'
UnboundLocalError: local variable 'shuffle' referenced before assignment

**Comment by wang-ps** [comment]
Thank you for pointing out this issue. I have fixed it. Please pull the latest code.

By the way, we recommend using the tensorflow-based implementation, instead of caffe.
