### ISSUE TITLE
octree visualization

### ISSUE THREAD

**Issue by christinazavou** [microsoft/O-CNN#96]
Hi,
I'm wondering if there is any code / software to visualize the .octree files !? 
Thanks in advance!

**Comment by wang-ps** [comment]
Yes, it can be downloaded via the following link: [octreeviewer.zip](https://github.com/microsoft/O-CNN/files/5013959/octreeviewer.zip)
It can be used to visualize octree files, points files, and mesh files. But it can only run on Win10 x64 system.

**Comment by jeannotes** [comment]
@wang-ps  any code for compile this exe? or ant other methods?
