### ISSUE TITLE
[DOUBT] Usage of ground truth octree in deconvolutions

### ISSUE THREAD

**Issue by apoorvkhattar** [microsoft/O-CNN#99]
Hi,
I was referring to your code about shape completion and I noticed that in the octree deconvolution layer, the ground truth octree (octree of the complete shape) was being passed as can be seen in line 60 of [network_completion.py](https://github.com/microsoft/O-CNN/blob/master/tensorflow/script/network_completion.py) i.e. 

`deconv = octree_deconv_bn_relu(deconv, octree1, d-1, channels[d], training,stride=2, kernel_size=[2])`

Can you please clarify what is the use of the ground truth octree?

**Comment by wang-ps** [comment]
Yes, in the training stage, the ground truth octrees are used in the decoder to make the training process stable and speed up the convergence. 
In the testing stage, only the newly generated octrees are used in the decoder.  Please refer to the function ` def decode_shape(self, convd, octree0, training, reuse=False)` defined in Line 93 of [network_completion.py](https://github.com/microsoft/O-CNN/blob/master/tensorflow/script/network_completion.py).  Here the `octree0` is the incomplete octree, and this function returns a complete octree.

**Comment by apoorvkhattar** [comment]
Thank you for clarifying.
